(function(){'use strict';
const D=window.ET_UNIFIED_GAME;if(!D||!D.questions)return;
const types=[
 ['Cannon Siege','💣','أطلق المدفع على الإجابة الصحيحة','سماء القلعة','🛡️','💣','float'],['Archery Master','🏹','صوّب السهم على الهدف الصحيح','ساحة التدريب','🏹','🏹','sway'],['Deep Sea Fishing','🎣','ارمِ الخطاف إلى الكلمة الصحيحة','أعماق البحر','🧑‍🎣','🪝','rise'],['Space Laser','🚀','أطلق الليزر على الكوكب الصحيح','المجرة','🚀','⚡','pulse'],['Ninja Shuriken','⭐','اقذف النجمة نحو الإجابة الصحيحة','معبد النينجا','🥷','⭐','zig'],['Bowling Strike','🎳','أسقط الدبابيس بالإجابة الصحيحة','مضمار البولينج','🎳','🎳','slide'],
 ['Soccer Goal','⚽','اركل الكرة إلى الهدف الصحيح','الملعب','⚽','⚽','slide'],['Basketball Hoop','🏀','صوّب الكرة داخل السلة الصحيحة','ملعب السلة','🏀','🏀','rise'],['Boomerang Throw','🪃','ارمِ البوميرانج إلى الإجابة الصحيحة','الوادي','🧑','🪃','sway'],['Spider Drop','🕷️','أنزل العنكبوت على الإجابة الصحيحة','بيت العنكبوت','🕷️','🕸️','drop'],['Heli Rescue','🚁','أنقذ الهدف الصحيح بالمروحية','منطقة الإنقاذ','🚁','🚁','drift'],['Thunder Strike','⚡','اضرب البرق على الإجابة الصحيحة','سماء العاصفة','🧙','⚡','pulse'],
 ['Volcano Defense','🌋','احمِ البركان بإجابة صحيحة','حافة البركان','🧑','🌋','pulse'],['Robot Tank','🤖','أطلق الدبابة على الهدف الصحيح','ساحة الروبوتات','🤖','🛡️','slide'],['Robot Train','🚂','وجّه القطار إلى الإجابة الصحيحة','محطة الروبوتات','🤖','🚂','drift'],['Lasso Rescue','🤠','التقط الإجابة الصحيحة بالحبل','المزرعة','🤠','🪢','sway'],['Magic Wand','🪄','لوّح بالعصا نحو الإجابة الصحيحة','مختبر السحر','🧙','🪄','zig'],['Billiard Shot','🎱','سدّد الكرة نحو الإجابة الصحيحة','طاولة البلياردو','🎱','🎱','slide'],
 ['UFO Capture','🛸','التقط الكوكب الصحيح بالمركبة','الفضاء','👽','🛸','orbit'],['Trapdoor Escape','🚪','افتح الباب الذي يحمل الإجابة الصحيحة','الممر السري','🧑','🔑','drop'],['Racecar Balance','🏎️','وجّه السيارة إلى الإجابة الصحيحة','حلبة السباق','🏎️','🏁','slide'],['Water Story','🌊','اسبح نحو الإجابة الصحيحة','عالم الماء','🤿','🌊','rise'],['Dart Talk','🎯','صوّب السهم على الإجابة الصحيحة','لوحة التصويب','🎯','🎯','zig'],['Slingshot Skills','🪨','أطلق المقلاع على الهدف الصحيح','ساحة المهارات','🧑','🪨','sway'],
 ['Whack-a-Mole','🔨','اضرب الحفرة التي تحمل الإجابة الصحيحة','حديقة الألعاب','🧑','🔨','pop'],['Balloon Builder','🎈','المس البالون الصحيح','سماء البالونات','🧑','🎈','rise'],['Boxing Choice','🥊','وجّه اللكمة إلى الإجابة الصحيحة','حلبة الملاكمة','🥊','🥊','shake'],['Paper Plane','✈️','أرسل الطائرة إلى الإجابة الصحيحة','سماء الورق','🧑','✈️','drift'],['Gold Miner','⛏️','احفر نحو الذهب الصحيح','منجم الذهب','🧑','⛏️','drop'],['Magnet Catch','🧲','اجذب الإجابة الصحيحة بالمغناطيس','مختبر المغناطيس','🧑','🧲','orbit'],
 ['Catapult Story','🏰','أطلق القصة الصحيحة بالمقلاع','قلعة القصص','🧑','🏰','sway'],['Ping Pong','🏓','أرسل الكرة إلى الإجابة الصحيحة','طاولة التنس','🏓','🏓','slide'],['Deep Diver','🤿','اغطس نحو الإجابة الصحيحة','قاع البحر','🤿','🌊','rise'],['Parachute','🪂','اهبط عند الإجابة الصحيحة','سماء الهبوط','🪂','🪂','drop'],['Karate Match','🥋','نفّذ الحركة عند الإجابة الصحيحة','معبد الكاراتيه','🥋','🥋','shake'],['Potion Lab','🧪','اخلط الجرعة ذات الإجابة الصحيحة','مختبر الجرعات','🧙','🧪','pulse']
].map((x,n)=>({u:Math.floor(n/6)+1,l:n%6+1,key:x[0].toLowerCase().replace(/[^a-z]+/g,'-'),name:x[0],icon:x[1],verb:x[2],scene:x[3],avatar:x[4],weapon:x[5],motion:x[6]}));
const lesson=Math.max(1,Number(D.lesson)||1),unit=Math.max(1,Number(D.unit)||1),type=types.find(x=>x.u===unit&&x.l===lesson)||types[(lesson-1)%types.length];
const gradeLabels={'primary-3':'الصف الثالث الابتدائي','primary-4':'الصف الرابع الابتدائي','primary-5':'الصف الخامس الابتدائي','primary-6':'الصف السادس الابتدائي','prep-1':'الصف الأول الإعدادي','prep-2':'الصف الثاني الإعدادي','prep-3':'الصف الثالث الإعدادي'};
const grade=String(D.grade||'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalize(q){const choices=Array.isArray(q.choices)?q.choices.map(x=>String(x??'')).filter(Boolean):[];let answer=Number(q.answer);if(!Number.isFinite(answer))answer=Number(q.correct);if(!Number.isFinite(answer))answer=0;answer=Math.max(0,Math.min(choices.length-1,answer));return {q:String(q.q||q.prompt||q.question||'').trim(),choices,answer};}
let bank=(D.questions||[]).map(normalize).filter(q=>q.q&&q.choices.length>=2);if(!bank.length)return;
let rounds=[];for(let i=0;i<Math.max(8,Math.min(10,bank.length));i++)rounds.push(bank[i%bank.length]);
let i=0,score=0,correct=0,locked=false;
const css=`
#et-unified-shell{position:fixed;inset:0;z-index:99990;display:flex;flex-direction:column;background:radial-gradient(circle at 50% 12%,#243a78 0,#111a43 42%,#070b1d 100%);color:#fff;font-family:Cairo,Arial,sans-serif;overflow:hidden}
#et-unified-shell *{box-sizing:border-box}#et-ug-hud{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:calc(env(safe-area-inset-top,0px) + 10px) clamp(10px,3vw,28px) 10px;background:rgba(5,10,28,.68);border-bottom:1px solid rgba(255,255,255,.12);z-index:3}#et-ug-hud strong{font-size:clamp(15px,2.8vw,24px)}#et-ug-hud small{display:block;color:#aab8eb;font-weight:800;font-size:11px}#et-ug-score{color:#ffd369}#et-ug-progress{height:6px;background:#1c2854}#et-ug-progress span{display:block;height:100%;width:0;background:linear-gradient(90deg,#22d3ee,#facc15);transition:width .35s ease}
#et-ug-main{position:relative;display:flex;flex:1;min-height:0;flex-direction:column;align-items:center;justify-content:center;padding:clamp(12px,3vh,28px) 12px 22px;overflow:auto}#et-ug-question{width:min(930px,94vw);text-align:center;z-index:5;margin-bottom:clamp(8px,2vh,18px)}#et-ug-question .badge{display:inline-flex;align-items:center;gap:8px;padding:6px 13px;border-radius:999px;background:rgba(41,211,194,.16);border:1px solid rgba(41,211,194,.45);color:#8ff9eb;font-weight:900;font-size:12px}#et-ug-question h1{font-size:clamp(18px,3.6vw,32px);line-height:1.45;margin:12px auto 0;max-width:880px;font-weight:900;text-shadow:0 3px 15px rgba(0,0,0,.3)}
#et-ug-scene{position:relative;width:min(930px,96vw);height:min(54vh,480px);min-height:285px;border-radius:32px;border:2px solid rgba(255,255,255,.18);overflow:hidden;box-shadow:0 20px 55px rgba(0,0,0,.35),inset 0 0 50px rgba(255,255,255,.05);background:linear-gradient(180deg,#19346c,#0b173a 72%,#10122d)}#et-ug-scene.motion-orbit{background:linear-gradient(180deg,#32166a,#10143d 72%,#12112d)}#et-ug-scene.motion-pulse{background:linear-gradient(180deg,#54244b,#14152f 72%,#12112d)}#et-ug-scene:before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 15% 20%,rgba(255,255,255,.85) 0 2px,transparent 3px),radial-gradient(circle at 72% 28%,rgba(255,255,255,.7) 0 1px,transparent 2px),radial-gradient(circle at 48% 12%,rgba(255,255,255,.8) 0 2px,transparent 3px),linear-gradient(135deg,transparent 48%,rgba(255,255,255,.06) 49% 51%,transparent 52%);background-size:auto,auto,auto,100% 100%;opacity:.72;pointer-events:none}#et-ug-scene:after{content:'';position:absolute;left:0;right:0;bottom:0;height:30%;background:linear-gradient(180deg,transparent,rgba(4,6,18,.75));pointer-events:none}
.et-ug-object{position:absolute;display:flex;align-items:center;justify-content:center;min-width:clamp(74px,12vw,122px);min-height:clamp(52px,8vw,78px);padding:10px 13px;border:2px solid rgba(255,255,255,.88);border-radius:22px;color:#fff;background:linear-gradient(145deg,#2685d9,#164a9d);font:900 clamp(14px,2.5vw,22px) Cairo;line-height:1.2;text-align:center;box-shadow:0 9px 0 rgba(4,24,73,.55),0 9px 26px rgba(0,0,0,.28);cursor:pointer;touch-action:manipulation;z-index:3;animation:et-float 3.2s ease-in-out infinite;transition:transform .25s ease,filter .25s ease,opacity .25s ease}.et-ug-object:nth-child(3n){background:linear-gradient(145deg,#e76b50,#9f2e54)}.et-ug-object:nth-child(4n){background:linear-gradient(145deg,#21ae9f,#176b86)}.et-ug-object:nth-child(5n){background:linear-gradient(145deg,#b56ce5,#5d3a9c)}.et-ug-object:hover{filter:brightness(1.18);transform:translateY(-5px) scale(1.04)}.et-ug-object.motion-sway{animation-name:et-sway}.et-ug-object.motion-rise{animation-name:et-rise}.et-ug-object.motion-pulse{animation-name:et-pulse}.et-ug-object.motion-zig{animation-name:et-zig}.et-ug-object.motion-slide{animation-name:et-slide}.et-ug-object.motion-drop{animation-name:et-drop}.et-ug-object.motion-drift{animation-name:et-drift}.et-ug-object.motion-orbit{animation-name:et-orbit}.et-ug-object.motion-pop{animation-name:et-pop}.et-ug-object.motion-shake{animation-name:et-shake}.et-ug-object.et-hit{animation:et-hit .58s ease forwards}.et-ug-object.et-wrong{animation:et-wrong .42s ease 2;filter:brightness(.65)}
#et-ug-avatar{position:absolute;left:50%;bottom:10px;transform:translateX(-50%);z-index:2;font-size:clamp(48px,11vw,92px);filter:drop-shadow(0 9px 5px rgba(0,0,0,.45));animation:et-bob 2.4s ease-in-out infinite;pointer-events:none}#et-ug-weapon{position:absolute;left:50%;bottom:76px;transform:translateX(-50%);z-index:2;font-size:clamp(28px,6vw,56px);opacity:.94;pointer-events:none}#et-ug-feedback{height:30px;margin-top:8px;font-weight:900;color:#ffd369;text-align:center;z-index:5}.et-good{color:#70f5b0!important}.et-bad{color:#ff9a9a!important}
#et-ug-help{color:#aab8eb;font-size:12px;font-weight:800;text-align:center;margin-top:4px}#et-ug-finish{position:absolute;inset:0;display:none;align-items:center;justify-content:center;z-index:20;background:rgba(5,9,27,.84);backdrop-filter:blur(10px);padding:20px}#et-ug-finish-card{width:min(470px,92vw);text-align:center;padding:30px 20px;border-radius:28px;background:linear-gradient(145deg,#213b7b,#111a43);border:2px solid #f5c84b;box-shadow:0 20px 60px rgba(0,0,0,.45)}#et-ug-finish-card .trophy{font-size:62px}#et-ug-finish-card h2{font-size:28px;margin:8px 0;color:#ffd369}#et-ug-finish-card p{color:#d7e1ff;font-weight:800;line-height:1.8}#et-ug-back{display:inline-flex;margin-top:14px;padding:11px 18px;border-radius:14px;background:#f5b932;color:#172147;text-decoration:none;font-weight:900;box-shadow:0 5px 0 #a8730b}
@keyframes et-float{0%,100%{margin-top:0}50%{margin-top:-13px}}@keyframes et-sway{0%,100%{transform:translate(-50%,-50%) rotate(-3deg)}50%{transform:translate(-50%,-50%) rotate(3deg) translateY(-9px)}}@keyframes et-rise{0%,100%{transform:translate(-50%,-50%)}50%{transform:translate(-50%,-50%) translateY(-17px)}}@keyframes et-pulse{0%,100%{filter:brightness(1)}50%{filter:brightness(1.5);transform:translate(-50%,-50%) scale(1.04)}}@keyframes et-zig{0%,100%{transform:translate(-50%,-50%) translateX(-7px)}50%{transform:translate(-50%,-50%) translateX(7px) translateY(-8px)}}@keyframes et-slide{0%,100%{transform:translate(-50%,-50%) translateX(-10px)}50%{transform:translate(-50%,-50%) translateX(10px)}}@keyframes et-drop{0%,100%{transform:translate(-50%,-50%) translateY(-10px)}50%{transform:translate(-50%,-50%) translateY(12px)}}@keyframes et-drift{0%,100%{transform:translate(-50%,-50%) translateX(-8px) translateY(4px)}50%{transform:translate(-50%,-50%) translateX(8px) translateY(-10px)}}@keyframes et-orbit{0%,100%{transform:translate(-50%,-50%) rotate(-4deg) scale(1)}50%{transform:translate(-50%,-50%) rotate(4deg) scale(1.08)}}@keyframes et-pop{0%,100%{transform:translate(-50%,-50%) scale(1)}50%{transform:translate(-50%,-50%) scale(1.12)}}@keyframes et-shake{0%,100%{transform:translate(-50%,-50%)}25%{transform:translate(-50%,-50%) rotate(-5deg)}75%{transform:translate(-50%,-50%) rotate(5deg)}}@keyframes et-bob{0%,100%{bottom:10px}50%{bottom:18px}}@keyframes et-hit{to{transform:scale(0) rotate(300deg);opacity:0}}@keyframes et-wrong{50%{margin-left:12px;filter:brightness(.55)}}
@media(max-width:560px){#et-ug-hud{padding-left:8px;padding-right:8px}#et-ug-scene{height:46vh;min-height:260px;border-radius:24px}.et-ug-object{min-width:68px;min-height:48px;padding:8px 9px;border-radius:17px;font-size:13px}#et-ug-avatar{font-size:54px}#et-ug-weapon{bottom:60px;font-size:30px}}
`;
const style=document.createElement('style');style.id='et-unified-gameplay-style';style.textContent=css;document.head.appendChild(style);document.documentElement.classList.add('et-unified-active');
const shell=document.createElement('div');shell.id='et-unified-shell';shell.innerHTML=`<div id="et-ug-hud"><div><small>${esc(gradeLabels[grade]||grade)} · Unit ${esc(D.unit||'')} · Lesson ${esc(D.lesson||'')}</small><strong>${type.icon} ${type.name}</strong></div><div id="et-ug-score">⭐ 0</div></div><div id="et-ug-progress"><span></span></div><main id="et-ug-main"><section id="et-ug-question"><span class="badge">${type.icon} ${esc(type.verb)}</span><h1></h1></section><section id="et-ug-scene" class="motion-${esc(type.motion)}" aria-label="${esc(type.scene)}"><div id="et-ug-avatar">${esc(type.avatar)}</div><div id="et-ug-weapon">${esc(type.weapon)}</div><div id="et-ug-targets"></div></section><div id="et-ug-feedback" aria-live="polite"></div><div id="et-ug-help">اختر العنصر الصحيح داخل المشهد</div></main><div id="et-ug-finish"><div id="et-ug-finish-card"><div class="trophy">🏆</div><h2>أحسنت يا بطل!</h2><p id="et-ug-final"></p><a id="et-ug-back" href="../../../games.html">العودة إلى ألعاب الكتاب</a></div></div>`;document.body.appendChild(shell);
const qEl=shell.querySelector('#et-ug-question h1'),zone=shell.querySelector('#et-ug-targets'),feedback=shell.querySelector('#et-ug-feedback'),scoreEl=shell.querySelector('#et-ug-score'),bar=shell.querySelector('#et-ug-progress span');
function positions(n){if(n===2)return[{left:25,top:48},{left:75,top:48}];if(n===4)return[{left:27,top:30},{left:73,top:30},{left:27,top:70},{left:73,top:70}];const out=[];for(let k=0;k<n;k++){const a=(Math.PI*2*k/n)-Math.PI/2,r=31;out.push({left:50+Math.cos(a)*r,top:50+Math.sin(a)*r});}return out;}
function load(){if(i>=rounds.length){finish();return;}locked=false;const q=rounds[i];qEl.textContent=q.q;feedback.textContent='';feedback.className='';bar.style.width=(i/rounds.length*100)+'%';zone.innerHTML='';const choices=q.choices.slice(0,4),pos=positions(choices.length);const correctText=choices[q.answer]||choices[0];const items=choices.map((text,idx)=>({text,ok:text===correctText})).sort(()=>Math.random()-.5);items.forEach((item,k)=>{const b=document.createElement('button');b.className='et-ug-object motion-'+type.motion;b.type='button';b.textContent=item.text;b.style.left=pos[k].left+'%';b.style.top=pos[k].top+'%';b.style.transform='translate(-50%,-50%)';b.style.animationDelay=(k*.16)+'s';b.onclick=()=>pick(b,item.ok);zone.appendChild(b);});}
function pick(btn,good){if(locked)return;locked=true;zone.querySelectorAll('button').forEach(b=>b.disabled=true);if(good){score+=100;correct++;scoreEl.textContent='⭐ '+score;feedback.textContent='إصابة صحيحة! أحسنت';feedback.className='et-good';btn.classList.add('et-hit');setTimeout(()=>{i++;load();},650);}else{feedback.textContent='حاول مرة أخرى في الجولة التالية';feedback.className='et-bad';btn.classList.add('et-wrong');setTimeout(()=>{i++;load();},900);}}
function finish(){bar.style.width='100%';shell.querySelector('#et-ug-final').textContent=`${esc(gradeLabels[grade]||grade)} · نتيجتك ${score} نقطة من ${rounds.length*100}. تم حفظ النتيجة في ترتيب صفك.`;shell.querySelector('#et-ug-finish').style.display='flex';try{if(window.EnglishtoonProfile?.award)window.EnglishtoonProfile.award(grade,score,{game:type.name+' U'+D.unit+' L'+D.lesson,score,correct});}catch(e){console.warn(e);}}
load();
})();
