/* =========================================================================
   بنك أسئلة كل الدروس — تم استخراجه من كتاب
   English Language - Performance Tasks and Assessments - Primary 3 - Term 1
   ========================================================================= */

const QUIZ_DATA = {

/* ============================= UNIT 1 ============================= */

u1l1: {
  unitTitleAr: "الوحدة الأولى", unitTitleEn: "Unit 1 - Let's Learn Together",
  lessonTitleAr: "الدرس الأول", lessonTitleEn: "Lesson 1 - Greetings and Introductions",
  questions: [
    { id:'q1', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'1- My name is ……… .',
      options:['goodbye','Youssef','years'], correct:1 },
    { id:'q2', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:"2- I'm ……… years old.",
      options:['nine','Lina','meet'], correct:0 },
    { id:'q3', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:"3- I'm from ……… .",
      options:['Egypt','Heba','Noha'], correct:0 },
    { id:'q4', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة (حرف كبير في البداية ونقطة/علامة استفهام في النهاية)',
      text:'my name is Ali', answers:['My name is Ali.'] },
    { id:'q5', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'how are you', answers:['How are you?'] },
    { id:'q6', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'meet - Nice - to - you!', answers:['Nice to meet you'] },
    { id:'q7', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'your - What - is - name?', answers:['What is your name'] },
    { id:'q8', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'name - Adam - My - is.', answers:['My name is Adam'] },
  ]
},

u1l2: {
  unitTitleAr: "الوحدة الأولى", unitTitleEn: "Unit 1 - Let's Learn Together",
  lessonTitleAr: "الدرس الثاني", lessonTitleEn: "Lesson 2 - Classroom Rules",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'your - Open - page 6 - on - book.', answers:['Open your book on page 6'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'go - to - bathroom - May - I - the?', answers:['May I go to the bathroom'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'your – hand - Raise - when – teacher - asks.', answers:['Raise your hand when teacher asks'] },
    { id:'q4', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة',
      text:'nwhe', answers:['when'] },
    { id:'q5', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة',
      text:'halew', answers:['whale'] },
    { id:'q6', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة',
      text:'hatw', answers:['what'] },
  ]
},

u1l3: {
  unitTitleAr: "الوحدة الأولى", unitTitleEn: "Unit 1 - Let's Learn Together",
  lessonTitleAr: "الدرس الثالث", lessonTitleEn: "Lesson 3 - Describing People",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة',
      text:'a-d-s', answers:['sad'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة',
      text:'f-u-l-h-l-p-e', answers:['helpful'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة',
      text:'r-g-n-a-y', answers:['angry'] },
    { id:'q4', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'has – She - green - eyes.', answers:['She has green eyes'] },
    { id:'q5', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'is – sister - She - my.', answers:['She is my sister'] },
    { id:'q6', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'today - How - you - are?', answers:['How are you today'] },
    { id:'q7', type:'text', mode:'containsAny', instruction:'اقرأ ثم أجب: "This is my friend Tala. She is very helpful and funny. She always helps her friends doing their homework. She has long black hair and brown eyes." — What is the friend\'s name?',
      text:'', answers:['Tala'] },
    { id:'q8', type:'text', mode:'containsAny', instruction:'كيف تساعد تالا أصدقاءها؟ (How does Tala help her friends?)',
      text:'', answers:['homework'] },
    { id:'q9', type:'text', mode:'containsAny', instruction:'ما نوع شخصية تالا؟ (What kind of person is Tala?)',
      text:'', answers:['helpful','funny'] },
  ]
},

u1l4: {
  unitTitleAr: "الوحدة الأولى", unitTitleEn: "Unit 1 - Let's Learn Together",
  lessonTitleAr: "الدرس الرابع", lessonTitleEn: "Lesson 4 - Daily Routines",
  questions: [
    { id:'q0', type:'text', mode:'containsAny', instruction:'اقرأ الفقرة ثم أجب على الأسئلة التالية: "My name is Youssef. I eat breakfast and then go to school. My brother is 6 years old. He is tall with brown hair. He wakes up at 7 a.m., eats breakfast at 7:30 and then he likes to play football." — When does Youssef\'s brother wake up?',
      text:'', answers:['7'] },
    { id:'q1', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:"Youssef's brother is ……… years old.",
      options:['5','10','6'], correct:2 },
    { id:'q2', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:"Youssef's brother goes to play ……… after breakfast.",
      options:['football','basketball','tennis'], correct:0 },
    { id:'q3', type:'text', mode:'containsAny', instruction:"What color is Youssef's brother's hair?",
      text:'', answers:['brown'] },
    { id:'q4', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'go- to –school-I - a.m.-at -8.', answers:['I go to school at 8 a.m'] },
    { id:'q5', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'bed- make- I-my.', answers:['I make my bed'] },
    { id:'q6', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'do-homework-I-my.', answers:['I do my homework'] },
  ]
},

/* ============================= UNIT 2 ============================= */

u2l1: {
  unitTitleAr: "الوحدة الثانية", unitTitleEn: "Unit 2 - My Family and I",
  lessonTitleAr: "الدرس الأول", lessonTitleEn: "Lesson 1 - Meet My Family",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'👧',
      text:'sierts', answers:['sister'] },
    { id:'q2', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'👵',
      text:'ndragtherom', answers:['grandmother'] },
    { id:'q3', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'👴',
      text:'clenu', answers:['uncle'] },
    { id:'q4', type:'mcq', instruction:'صحح الكلمة الخطأ: اختر الضمير الصحيح', text:'I have a cat. ……… cat is cute.',
      options:['My','His','Her'], correct:0 },
    { id:'q5', type:'mcq', instruction:'صحح الكلمة الخطأ: اختر الضمير الصحيح', text:'My grandfather has a farm. ……… farm is big.',
      options:['Her','His','My'], correct:1 },
    { id:'q6', type:'mcq', instruction:'صحح الكلمة الخطأ: اختر الضمير الصحيح', text:'This is Laila. ……… cap is pink.',
      options:['His','Her','My'], correct:1 },
    { id:'q7', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (my - his - her)', text:"I'm Mona. I live in a big house with ……… family.",
      options:['my','his','her'], correct:0 },
    { id:'q8', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (my - his - her)', text:'I help my friend doing ……… homework.',
      options:['my','his','her'], correct:2 },
    { id:'q9', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (my - his - her)', text:'I help my father clean ……… car.',
      options:['my','his','her'], correct:1 },
  ]
},

u2l2: {
  unitTitleAr: "الوحدة الثانية", unitTitleEn: "Unit 2 - My Family and I",
  lessonTitleAr: "الدرس الثاني", lessonTitleEn: "Lesson 2 - Family Traditions and Celebrations",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين اسم المناسبة', emoji:'🥚🌿',
      text:'S-a-h-m El N-s-s-i-m-e', answers:['sham el nessim','sham elnessim','sham el-nessim'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين اسم المناسبة', emoji:'💐',
      text:"t-h-e-r's-M-o D-y-a", answers:["mother's day","mothers day"] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين اسم المناسبة', emoji:'🏮',
      text:'i-E-d Al r-i-t-F', answers:['eid al-fitr','eid al fitr','eid alfitr'] },
    { id:'q4', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (brave - favorite - October)', text:'My ……… celebration is 6th of October.',
      options:['brave','favorite','October'], correct:1 },
    { id:'q5', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (brave - favorite - October)', text:'My favorite celebration is 6th of ……… .',
      options:['brave','favorite','October'], correct:2 },
    { id:'q6', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (brave - favorite - October)', text:'It reminds us how ……… are the Egyptian soldiers.',
      options:['brave','favorite','October'], correct:0 },
    { id:'q7', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (exit - exam - example)', text:'I do well in my math ……… .',
      options:['exit','exam','example'], correct:1 },
    { id:'q8', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (exit - exam - example)', text:'The ……… of our school is near the garden.',
      options:['exit','exam','example'], correct:0 },
    { id:'q9', type:'mcq', instruction:'اختر الكلمة المناسبة من الصندوق (exit - exam - example)', text:'I answer one ……… in the class.',
      options:['exit','exam','example'], correct:2 },
  ]
},

u2l3: {
  unitTitleAr: "الوحدة الثانية", unitTitleEn: "Unit 2 - My Family and I",
  lessonTitleAr: "الدرس الثالث", lessonTitleEn: "Lesson 3 - My Family Helps Me Grow",
  questions: [
    { id:'q1', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'My mother ……… us food every day.',
      options:['cooks','takes','helps'], correct:0 },
    { id:'q2', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'My brother ……… me do my homework.',
      options:['helps','cooks','reads'], correct:0 },
    { id:'q3', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'My father ……… me a story.',
      options:['read','reads','cooks'], correct:1 },
    { id:'q4', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'🐘',
      text:'e-l-e-h-p-n-a-t', answers:['elephant'] },
    { id:'q5', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'📱',
      text:'h-p-o-e-n', answers:['phone'] },
    { id:'q6', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'📷',
      text:'t-o-h-p-o', answers:['photo'] },
    { id:'q7', type:'mcq', instruction:'اختر الضمير الصحيح', text:"Hamza's ……… plays with him.",
      options:['my','his','her'], correct:1 },
    { id:'q8', type:'text', mode:'containsAny', instruction:'أكمل: "I\'m Hamza. I love my family..." — Hamza loves his ……… .',
      text:'', answers:['family'] },
    { id:'q9', type:'text', mode:'containsAny', instruction:'أكمل: My ……… takes me to school.',
      text:'', answers:['father'] },
    { id:'q10', type:'text', mode:'containsAny', instruction:'أكمل: My mother ……… me lunch.',
      text:'', answers:['cooks'] },
  ]
},

u2l4: {
  unitTitleAr: "الوحدة الثانية", unitTitleEn: "Unit 2 - My Family and I",
  lessonTitleAr: "الدرس الرابع", lessonTitleEn: "Lesson 4 - Jobs in My Family",
  questions: [
    { id:'q1', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'He is a teacher. He ……… .',
      options:['works at school','helps patients','bakes cake'], correct:0 },
    { id:'q2', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'She is a pilot. She ……… .',
      options:['bakes bread','travels around the world','works at school'], correct:1 },
    { id:'q3', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'My mom is a doctor. She ……… .',
      options:['helps patients','works at school','bakes bread'], correct:0 },
    { id:'q4', type:'text', mode:'loose', instruction:'انظر للإيموجي واكتب اسم المهنة', emoji:'🧑\u200d🌾',
      text:'', answers:['farmer'] },
    { id:'q5', type:'text', mode:'loose', instruction:'انظر للإيموجي واكتب اسم المهنة', emoji:'👩\u200d⚕️',
      text:'', answers:['doctor'] },
    { id:'q6', type:'text', mode:'loose', instruction:'انظر للإيموجي واكتب اسم المهنة', emoji:'👨\u200d✈️',
      text:'', answers:['pilot'] },
    { id:'q7', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'aunt - My - a - doctor - is.', answers:['My aunt is a doctor'] },
    { id:'q8', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'pilot - is - She - a.', answers:['She is a pilot'] },
    { id:'q9', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'around - the – world - He – travels.', answers:['He travels around the world'] },
    { id:'q10', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'bakes- delicious- food- The- baker.', answers:['The baker bakes delicious food'] },
  ]
},

/* ============================= UNIT 3 ============================= */

u3l1: {
  unitTitleAr: "الوحدة الثالثة", unitTitleEn: "Unit 3 - New Adventures",
  lessonTitleAr: "الدرس الأول", lessonTitleEn: "Lesson 1 - Places Around Me",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'📚',
      text:'b-r-a-r-y-i-l', answers:['library'] },
    { id:'q2', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'🏠',
      text:'o-u-e-s-h', answers:['house'] },
    { id:'q3', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'🛒',
      text:'u-p-r-s-e market', answers:['supermarket','super market'] },
    { id:'q4', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'the- He- went-to –library.', answers:['He went to the library'] },
    { id:'q5', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'My- shopping- mom- went.', answers:['My mom went shopping'] },
    { id:'q6', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'played-He-the-park-at.', answers:['He played at the park'] },
    { id:'q7', type:'text', mode:'containsAny', instruction:'اقرأ: "Youssef left his house early in the morning. First, he went to the library to read a book. Then, he and his mom went shopping at the supermarket. In the afternoon, he played at the park." — Youssef went to the ……… to read a book.',
      text:'', answers:['library'] },
    { id:'q8', type:'text', mode:'containsAny', instruction:'In the ………, he played at the park.',
      text:'', answers:['afternoon'] },
    { id:'q9', type:'text', mode:'containsAny', instruction:'In the morning, he ……… his house early.',
      text:'', answers:['left'] },
    { id:'q10', type:'text', mode:'containsAny', instruction:'Youssef and his mom went ……… .',
      text:'', answers:['shopping'] },
  ]
},

u3l2: {
  unitTitleAr: "الوحدة الثالثة", unitTitleEn: "Unit 3 - New Adventures",
  lessonTitleAr: "الدرس الثاني", lessonTitleEn: "Lesson 2 - Egypt's Landmarks",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'🔺',
      text:'The p-r-a-m-y-d-i-s of Giza', answers:['pyramids'] },
    { id:'q2', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'📚',
      text:'Alexandria i-b-r-a-l-r-y', answers:['library'] },
    { id:'q3', type:'text', mode:'loose', instruction:'انظر للإيموجي ورتب الحروف لتكوين الكلمة', emoji:'🗼',
      text:'Cairo w-T-o-e-r', answers:['tower'] },
    { id:'q4', type:'mcq', instruction:'اختر الكلمة ذات الصوت المختلف عن الباقي', text:'buzz - pull - tell',
      options:['buzz','pull','tell'], correct:0 },
    { id:'q5', type:'mcq', instruction:'اختر الكلمة ذات الصوت المختلف عن الباقي', text:'off - less - staff',
      options:['off','less','staff'], correct:1 },
    { id:'q6', type:'mcq', instruction:'اختر الكلمة ذات الصوت المختلف عن الباقي', text:'jazz - bell - fuzz',
      options:['jazz','bell','fuzz'], correct:1 },
    { id:'q7', type:'text', mode:'containsAny', instruction:'اقرأ: "Ayla visited the Cairo Tower with her family..." — Ayla visited the ……… with her family and took pictures.',
      text:'', answers:['tower'] },
    { id:'q8', type:'text', mode:'containsAny', instruction:'At the Alexandria library, she ……… fun books.',
      text:'', answers:['read'] },
    { id:'q9', type:'text', mode:'containsAny', instruction:'She read ……… books.',
      text:'', answers:['fun'] },
    { id:'q10', type:'text', mode:'containsAny', instruction:'It is the best ……… ever.',
      text:'', answers:['holiday'] },
  ]
},

u3l3: {
  unitTitleAr: "الوحدة الثالثة", unitTitleEn: "Unit 3 - New Adventures",
  lessonTitleAr: "الدرس الثالث", lessonTitleEn: "Lesson 3 - Map It Out",
  questions: [
    { id:'q1', type:'mcq', instruction:'انظر للإيموجي واختر حرف الجر الصحيح', emoji:'🐶⛺', text:'The dog is ……… the box.',
      options:['under','between','in'], correct:0 },
    { id:'q2', type:'mcq', instruction:'انظر للإيموجي واختر حرف الجر الصحيح', emoji:'📦🐱📦', text:'The cat is ……… the boxes.',
      options:['between','under','in'], correct:0 },
    { id:'q3', type:'mcq', instruction:'انظر للإيموجي واختر حرف الجر الصحيح', emoji:'📦🐱', text:'The cat is ……… the box.',
      options:['in','under','between'], correct:0 },
    { id:'q4', type:'mcq', instruction:'اكمل الفقرة من الكلمات (stuck - stick - between - car)', text:'Samy was playing in his room when his toy ……… rolled under the couch.',
      options:['stuck','stick','between','car'], correct:3 },
    { id:'q5', type:'mcq', instruction:'اكمل الفقرة من الكلمات (stuck - stick - between - car)', text:'He checked ……… the two chairs.',
      options:['stuck','stick','between','car'], correct:2 },
    { id:'q6', type:'mcq', instruction:'اكمل الفقرة من الكلمات (stuck - stick - between - car)', text:'and saw it was ……… .',
      options:['stuck','stick','between','car'], correct:0 },
    { id:'q7', type:'mcq', instruction:'اكمل الفقرة من الكلمات (stuck - stick - between - car)', text:'He used a ……… to pull it out.',
      options:['stuck','stick','between','car'], correct:1 },
  ]
},

u3l4: {
  unitTitleAr: "الوحدة الثالثة", unitTitleEn: "Unit 3 - New Adventures",
  lessonTitleAr: "الدرس الرابع", lessonTitleEn: "Lesson 4 - A School Trip to The Zoo",
  questions: [
    { id:'q1', type:'mcq', instruction:'ما هو الماضي البسيط لهذا الفعل؟', text:"What is the past simple of 'close'?",
      options:['closed','climbed','liked','played'], correct:0 },
    { id:'q2', type:'mcq', instruction:'ما هو الماضي البسيط لهذا الفعل؟', text:"What is the past simple of 'climb'?",
      options:['closed','climbed','liked','played'], correct:1 },
    { id:'q3', type:'mcq', instruction:'ما هو الماضي البسيط لهذا الفعل؟', text:"What is the past simple of 'like'?",
      options:['closed','climbed','liked','played'], correct:2 },
    { id:'q4', type:'mcq', instruction:'ما هو الماضي البسيط لهذا الفعل؟', text:"What is the past simple of 'play'?",
      options:['closed','climbed','liked','played'], correct:3 },
    { id:'q5', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'Noor ……… to school two days ago.',
      options:['walk','walked','walking'], correct:1 },
    { id:'q6', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'They ……… the tree yesterday.',
      options:['climbs','climbing','climbed'], correct:2 },
    { id:'q7', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'The girl ……… with her ball last week.',
      options:['play','playing','played'], correct:2 },
    { id:'q8', type:'text', mode:'containsAny', instruction:'اقرأ: "Last Sunday, Grade six students went on a trip to the Pyramids in Giza..." — When did the students go to the pyramids?',
      text:'', answers:['sunday'] },
    { id:'q9', type:'text', mode:'containsAny', instruction:'What animals did they see?',
      text:'', answers:['camels','horses'] },
  ]
},

/* ============================= UNIT 4 ============================= */

u4l1: {
  unitTitleAr: "الوحدة الرابعة", unitTitleEn: "Unit 4 - Let's Tell Stories",
  lessonTitleAr: "الدرس الأول", lessonTitleEn: "Lesson 1 - How We Feel",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'were- They- playing- in-park-the.', answers:['They were playing in the park'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'cat- The – jumped- high.', answers:['The cat jumped high'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'was- hole- The- small.', answers:['The hole was small'] },
    { id:'q4', type:'mcq', instruction:'حوّل الفعل إلى الماضي البسيط', text:'I ……… shopping with my mom. (go)',
      options:['go','goes','went'], correct:2 },
    { id:'q5', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'We ……… happy when we went to the birthday party.',
      options:['was','were','is'], correct:1 },
    { id:'q6', type:'mcq', instruction:'حوّل الفعل إلى الماضي البسيط', text:'He ……… the dog out angrily. (pull)',
      options:['pull','pulled','pulling'], correct:1 },
    { id:'q7', type:'mcq', instruction:'أي كلمة تحتوي على صوت |k|؟', text:'Which word has the |k| sound?',
      options:['car','yesterday','played','morning'], correct:0 },
  ]
},

u4l2: {
  unitTitleAr: "الوحدة الرابعة", unitTitleEn: "Unit 4 - Let's Tell Stories",
  lessonTitleAr: "الدرس الثاني", lessonTitleEn: "Lesson 2 - A Helping Hand",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'went- Sara- the- to-park.', answers:['Sara went to the park'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'knee- Sara – fell- and-hurt- her.', answers:['Sara fell and hurt her knee'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'felt-They-happy-proud- and.', answers:['They felt happy and proud'] },
    { id:'q4', type:'mcq', instruction:'اختر أداة الربط الصحيحة', text:'Malek played football ……… he fell.',
      options:['then','but','and'], correct:1 },
    { id:'q5', type:'mcq', instruction:'اختر أداة الربط الصحيحة', text:'I do my homework …. help my mom in the kitchen.',
      options:['then','but','and'], correct:2 },
    { id:'q6', type:'mcq', instruction:'اختر الإجابة الصحيحة', text:'Yesterday, they ……… tennis after school.',
      options:['played','sleep','cooked'], correct:0 },
    { id:'q7', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'we went to the supermarket', answers:['We went to the supermarket.'] },
    { id:'q8', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'i draw a picture on the board', answers:['I draw a picture on the board.'] },
    { id:'q9', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'we can see the elephant at the zoo', answers:['We can see the elephant at the zoo.'] },
  ]
},

u4l3: {
  unitTitleAr: "الوحدة الرابعة", unitTitleEn: "Unit 4 - Let's Tell Stories",
  lessonTitleAr: "الدرس الثالث", lessonTitleEn: "Lesson 3 - A Big Win",
  questions: [
    { id:'q1', type:'mcq', instruction:'اكمل الفقرة من الكلمات (goal - nervous - mistakes - football)', text:'Omar was ……… before his first match.',
      options:['goal','nervous','mistakes','football'], correct:1 },
    { id:'q2', type:'mcq', instruction:'اكمل الفقرة من الكلمات (goal - nervous - mistakes - football)', text:'before his first ……… match.',
      options:['goal','nervous','mistakes','football'], correct:3 },
    { id:'q3', type:'mcq', instruction:'اكمل الفقرة من الكلمات (goal - nervous - mistakes - football)', text:'he was worried about making ……… .',
      options:['goal','nervous','mistakes','football'], correct:2 },
    { id:'q4', type:'mcq', instruction:'اكمل الفقرة من الكلمات (goal - nervous - mistakes - football)', text:'after he scored a ………, Omar felt proud.',
      options:['goal','nervous','mistakes','football'], correct:0 },
    { id:'q5', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'scored-Omar-goal-a.', answers:['Omar scored a goal'] },
    { id:'q6', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'felt-Omar-proud-himself-of.', answers:['Omar felt proud of himself'] },
    { id:'q7', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'was-worried-making-mistakes- Omar- about', answers:['Omar was worried about making mistakes'] },
    { id:'q8', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'he was tired because he slept late', answers:['He was tired because he slept late.'] },
    { id:'q9', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'eyad was shy when he fell in the garden', answers:['Eyad was shy when he fell in the garden.'] },
    { id:'q10', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:"he was worried, but he didn't give up", answers:["He was worried, but he didn't give up."] },
  ]
},

/* ============================= UNIT 5 ============================= */

u5l1: {
  unitTitleAr: "الوحدة الخامسة", unitTitleEn: "Unit 5 - Together Is Better",
  lessonTitleAr: "الدرس الأول", lessonTitleEn: "Lesson 1 - Teamwork & Chores",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة', emoji:'🛏️',
      text:'d-i-y-t (tidy up the bed)', answers:['tidy'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة', emoji:'🤗',
      text:'a-r-e-c', answers:['care'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة', emoji:'🍭🤝',
      text:'a-r-h-s-e', answers:['share'] },
    { id:'q4', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'donates-Omar-clothes.', answers:['Omar donates clothes'] },
    { id:'q5', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'wins-Omar-match-football-the.', answers:['Omar wins the football match'] },
    { id:'q6', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'sister-with-food-shares-Sara-her.', answers:['Sara shares food with her sister'] },
    { id:'q7', type:'mcq', instruction:'اكمل الفقرة من الكلمات (together - home - chores - tidy)', text:'Their mother asks them to do some ……… .',
      options:['together','home','chores','tidy'], correct:2 },
    { id:'q8', type:'mcq', instruction:'اكمل الفقرة من الكلمات (together - home - chores - tidy)', text:'First, they ……… up the living room.',
      options:['together','home','chores','tidy'], correct:3 },
    { id:'q9', type:'mcq', instruction:'اكمل الفقرة من الكلمات (together - home - chores - tidy)', text:'Mona and Karim work ……… and share the chores.',
      options:['together','home','chores','tidy'], correct:0 },
  ]
},

u5l2: {
  unitTitleAr: "الوحدة الخامسة", unitTitleEn: "Unit 5 - Together Is Better",
  lessonTitleAr: "الدرس الثاني", lessonTitleEn: "Lesson 2 - Teamwork at School",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'finds-Youssef-a-idea-good.', answers:['Youssef finds a good idea'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'work-They-a – team-as.', answers:['They work as a team'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'their-plan – They-project.', answers:['They plan their project'] },
    { id:'q4', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'gum - good - giraffe',
      options:['gum','good','giraffe'], correct:2 },
    { id:'q5', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'gum - green - dog',
      options:['gum','green','dog'], correct:2 },
    { id:'q6', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'big - dog - page',
      options:['big','dog','page'], correct:2 },
    { id:'q7', type:'mcq', instruction:'اكمل الفقرة من الكلمات (good job - ideas - project - helped)', text:'Salma and Youssef had a ……… at school.',
      options:['good job','ideas','project','helped'], correct:2 },
    { id:'q8', type:'mcq', instruction:'اكمل الفقرة من الكلمات (good job - ideas - project - helped)', text:'Then, they started to share ……… .',
      options:['good job','ideas','project','helped'], correct:1 },
    { id:'q9', type:'mcq', instruction:'اكمل الفقرة من الكلمات (good job - ideas - project - helped)', text:'When Salma felt tired, Youssef ……… her.',
      options:['good job','ideas','project','helped'], correct:3 },
    { id:'q10', type:'mcq', instruction:'اكمل الفقرة من الكلمات (good job - ideas - project - helped)', text:'Their teacher was happy and said, "………!"',
      options:['good job','ideas','project','helped'], correct:0 },
  ]
},

u5l3: {
  unitTitleAr: "الوحدة الخامسة", unitTitleEn: "Unit 5 - Together Is Better",
  lessonTitleAr: "الدرس الثالث", lessonTitleEn: "Lesson 3 - Teamwork in Sports",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'pass-They –to-started-the-ball.', answers:['They started to pass the ball'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'together-They-won.', answers:['They won together'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'made-game –Teamwork-the-fun.', answers:['Teamwork made the game fun'] },
    { id:'q4', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'gum - page - giraffe',
      options:['gum','page','giraffe'], correct:0 },
    { id:'q5', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'Egypt - green - huge',
      options:['Egypt','green','huge'], correct:1 },
    { id:'q6', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'big - huge - good',
      options:['big','huge','good'], correct:1 },
    { id:'q7', type:'mcq', instruction:'اكمل الفقرة من الكلمات (scored - team - coach - football match)', text:'Mazen and his friends played ……… at school.',
      options:['scored','team','coach','football match'], correct:3 },
    { id:'q8', type:'mcq', instruction:'اكمل الفقرة من الكلمات (scored - team - coach - football match)', text:'their ……… said, "Work as a team!"',
      options:['scored','team','coach','football match'], correct:2 },
    { id:'q9', type:'mcq', instruction:'اكمل الفقرة من الكلمات (scored - team - coach - football match)', text:'"Work as a ………!"',
      options:['scored','team','coach','football match'], correct:1 },
    { id:'q10', type:'mcq', instruction:'اكمل الفقرة من الكلمات (scored - team - coach - football match)', text:'Karim ……… .',
      options:['scored','team','coach','football match'], correct:0 },
  ]
},

u5l4: {
  unitTitleAr: "الوحدة الخامسة", unitTitleEn: "Unit 5 - Together Is Better",
  lessonTitleAr: "الدرس الرابع", lessonTitleEn: "Lesson 4 - I Help My Community!",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'Salma-wants-help-to-neighborhood-her.', answers:['Salma wants to help her neighborhood'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'donate-They-and – clothes-toys.', answers:['They donate clothes and toys'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'the-makes –Teamwork-community-better.', answers:['Teamwork makes the community better'] },
    { id:'q4', type:'order', instruction:'رتب الجمل بالترتيب الصحيح للأحداث (1، 2، 3)',
      sentences:[
        { text:'Then, they plant trees near the school.', correct:2 },
        { text:'Finally, they are proud to help.', correct:3 },
        { text:'First, the children want to help their neighborhood.', correct:1 },
      ] },
    { id:'q5', type:'mcq', instruction:'اكمل الحوار من الكلمات (clean - together - donate - flowers)', text:'Omar: I am helping ……… the park.',
      options:['clean','together','donate','flowers'], correct:0 },
    { id:'q6', type:'mcq', instruction:'اكمل الحوار من الكلمات (clean - together - donate - flowers)', text:"Omar: Let's work ……… .",
      options:['clean','together','donate','flowers'], correct:1 },
    { id:'q7', type:'mcq', instruction:'اكمل الحوار من الكلمات (clean - together - donate - flowers)', text:'Sara: We can plant ……… .',
      options:['clean','together','donate','flowers'], correct:3 },
    { id:'q8', type:'mcq', instruction:'اكمل الحوار من الكلمات (clean - together - donate - flowers)', text:'Omar: And we can ……… books to the school library.',
      options:['clean','together','donate','flowers'], correct:2 },
  ]
},

/* ============================= UNIT 6 ============================= */

u6l1: {
  unitTitleAr: "الوحدة السادسة", unitTitleEn: "Unit 6 - Dare to Dream",
  lessonTitleAr: "الدرس الأول", lessonTitleEn: "Lesson 1 - My Goal, My Dream",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة', emoji:'🩺',
      text:'o-g-l-a', answers:['goal'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة', emoji:'🪜',
      text:'t-s-e-p', answers:['step'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الحروف لتكوين كلمة صحيحة', emoji:'🎉',
      text:'c-l-e-b-e-e-t-a-r', answers:['celebrate'] },
    { id:'q4', type:'mcq', instruction:'اختر الشكل الصحيح للفعل', text:'Youssef is ……… a goal.',
      options:['scored','scoring','score'], correct:1 },
    { id:'q5', type:'mcq', instruction:'اختر الشكل الصحيح للفعل', text:'Children ……… celebrating.',
      options:['is','are','was'], correct:1 },
    { id:'q6', type:'mcq', instruction:'اختر الشكل الصحيح للفعل', text:'They are ……… to win the match.',
      options:['try','trying','tries'], correct:1 },
    { id:'q7', type:'mcq', instruction:'اكمل الفقرة من الكلمات (goal - playing - kicking - proud)', text:'He is ……… the ball and splashing in the mud.',
      options:['goal','playing','kicking','proud'], correct:2 },
    { id:'q8', type:'mcq', instruction:'اكمل الفقرة من الكلمات (goal - playing - kicking - proud)', text:'Now, he is ……… a match with his friends.',
      options:['goal','playing','kicking','proud'], correct:1 },
    { id:'q9', type:'mcq', instruction:'اكمل الفقرة من الكلمات (goal - playing - kicking - proud)', text:'He is scoring a ……… .',
      options:['goal','playing','kicking','proud'], correct:0 },
    { id:'q10', type:'mcq', instruction:'اكمل الفقرة من الكلمات (goal - playing - kicking - proud)', text:'and is feeling very ……… .',
      options:['goal','playing','kicking','proud'], correct:3 },
  ]
},

u6l2: {
  unitTitleAr: "الوحدة السادسة", unitTitleEn: "Unit 6 - Dare to Dream",
  lessonTitleAr: "الدرس الثاني", lessonTitleEn: "Lesson 2 - A Day to Remember",
  questions: [
    { id:'q1', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'split - spray - splash',
      options:['split','spray','splash'], correct:1 },
    { id:'q2', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'spray - spring - split',
      options:['spray','spring','split'], correct:2 },
    { id:'q3', type:'mcq', instruction:'اختر الكلمة المختلفة عن الباقي', text:'screen - string - scream',
      options:['screen','string','scream'], correct:1 },
    { id:'q4', type:'text', mode:'loose', instruction:'اكتب الفعل بصيغة المضارع المستمر (ing)',
      text:"Mona is ……… (learn) how to ride her bike.", answers:['learning'] },
    { id:'q5', type:'text', mode:'loose', instruction:'اكتب الفعل بصيغة المضارع المستمر (ing)',
      text:'She is ……… (practice) every day in the garden.', answers:['practicing','practising'] },
    { id:'q6', type:'mcq', instruction:'اكمل الفقرة من الكلمات (bike - pedals - success)', text:'Mona is learning how to ride her red ……… .',
      options:['bike','pedals','success'], correct:0 },
    { id:'q7', type:'mcq', instruction:'اكمل الفقرة من الكلمات (bike - pedals - success)', text:'She is pushing her feet on the ……… .',
      options:['bike','pedals','success'], correct:1 },
    { id:'q8', type:'mcq', instruction:'اكمل الفقرة من الكلمات (bike - pedals - success)', text:'Mona is showing that practice brings ……… .',
      options:['bike','pedals','success'], correct:2 },
  ]
},

u6l3: {
  unitTitleAr: "الوحدة السادسة", unitTitleEn: "Unit 6 - Dare to Dream",
  lessonTitleAr: "الدرس الثالث", lessonTitleEn: "Lesson 3 - I Did It",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'the-He –questions-answered.', answers:['He answered the questions'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'felt-Tamer-proud – very.', answers:['Tamer felt very proud'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'nervous –Tamer-felt.', answers:['Tamer felt nervous'] },
    { id:'q4', type:'order', instruction:'رتب الجمل بالترتيب الصحيح للأحداث (1، 2، 3)',
      sentences:[
        { text:'Then, he answered all the questions.', correct:2 },
        { text:'Finally, he celebrated with his family.', correct:3 },
        { text:'First, Tamer studied hard.', correct:1 },
      ] },
    { id:'q5', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'who did Tamer celebrate with', answers:['Who did Tamer celebrate with?'] },
    { id:'q6', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'they won the race', answers:['They won the race.'] },
  ]
},

u6l4: {
  unitTitleAr: "الوحدة السادسة", unitTitleEn: "Unit 6 - Dare to Dream",
  lessonTitleAr: "الدرس الرابع", lessonTitleEn: "Lesson 4 - Helping Others Succeed",
  questions: [
    { id:'q1', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'is-Yara –runner-a fast.', answers:['Yara is a fast runner'] },
    { id:'q2', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'ran-They-together- won- and.', answers:['They ran together and won'] },
    { id:'q3', type:'text', mode:'loose', instruction:'رتب الكلمات لتكوين جملة صحيحة',
      text:'happy –Yara-felt- race-on-the.', answers:['Yara felt happy on the race'] },
    { id:'q4', type:'mcq', instruction:'أي كلمة في القصة هي فعل حركة (action verb)؟', text:'Sara is a fast runner. She practices every day at the school field.',
      options:['practices','fast','school','red'], correct:0 },
    { id:'q5', type:'mcq', instruction:'أي كلمة في القصة هي فعل حركة (action verb)؟', text:'They both celebrated their success with big cheers.',
      options:['Sara','celebrated','happy','day'], correct:1 },
    { id:'q6', type:'text', mode:'exact', instruction:'أعد كتابة الجملة بعلامات الترقيم الصحيحة',
      text:'they ran every day at the school field', answers:['They ran every day at the school field.'] },
  ]
},

};
