const CACHE_NAME = 'english-toon-v20260721021103';
const urlsToCache = [
    "/",
    "/.gitattributes",
    "/admin.html",
    "/check_images.py",
    "/dashboard.html",
    "/fix-alert.py",
    "/fix-arabic.js",
    "/fix-arabic.ps1",
    "/fix-arabic.py",
    "/fix-html-encoding.py",
    "/fix-meta.py",
    "/games_map.json",
    "/generate-3d-assets-v2.ps1",
    "/generate-3d-assets.ps1",
    "/grade.html",
    "/import-games.py",
    "/import-prep2.py",
    "/import_games.js",
    "/import_games.ps1",
    "/index.html",
    "/inject-enhancements.py",
    "/inject_emojis.ps1",
    "/inject_enhancements.ps1",
    "/inject_sentences.ps1",
    "/migrate-games.ps1",
    "/migrate-games.py",
    "/protect_games.ps1",
    "/README.md",
    "/regenerate_json.ps1",
    "/test-bytes.py",
    "/test-decode.py",
    "/test_apple.jpg",
    "/unit.html",
    "/assets/images/words/ant.jpg",
    "/assets/images/words/apple.jpg",
    "/assets/images/words/arm.jpg",
    "/assets/images/words/arrow.jpg",
    "/assets/images/words/axe.jpg",
    "/assets/images/words/bag.jpg",
    "/assets/images/words/bee.jpg",
    "/assets/images/words/bird.jpg",
    "/assets/images/words/blue.jpg",
    "/assets/images/words/board.jpg",
    "/assets/images/words/book.jpg",
    "/assets/images/words/brother.jpg",
    "/assets/images/words/bus.jpg",
    "/assets/images/words/butterfly.jpg",
    "/assets/images/words/chair.jpg",
    "/assets/images/words/desk.jpg",
    "/assets/images/words/dog.jpg",
    "/assets/images/words/doll.jpg",
    "/assets/images/words/door.jpg",
    "/assets/images/words/drum.jpg",
    "/assets/images/words/duck.jpg",
    "/assets/images/words/father.jpg",
    "/assets/images/words/five.jpg",
    "/assets/images/words/flower.jpg",
    "/assets/images/words/flowers.jpg",
    "/assets/images/words/four.jpg",
    "/assets/images/words/Goodbye.jpg",
    "/assets/images/words/grandfather.jpg",
    "/assets/images/words/grandmother.jpg",
    "/assets/images/words/grass.jpg",
    "/assets/images/words/hair.jpg",
    "/assets/images/words/hana.jpg",
    "/assets/images/words/hands.jpg",
    "/assets/images/words/hany.jpg",
    "/assets/images/words/hat.jpg",
    "/assets/images/words/Hello.jpg",
    "/assets/images/words/horse.jpg",
    "/assets/images/words/house.jpg",
    "/assets/images/words/ill.jpg",
    "/assets/images/words/in.jpg",
    "/assets/images/words/ink.jpg",
    "/assets/images/words/insect.jpg",
    "/assets/images/words/miss_mona.jpg",
    "/assets/images/words/mother.jpg",
    "/assets/images/words/nail.jpg",
    "/assets/images/words/neck.jpg",
    "/assets/images/words/net.jpg",
    "/assets/images/words/nose.jpg",
    "/assets/images/words/nurse.jpg",
    "/assets/images/words/one.jpg",
    "/assets/images/words/open your books.jpg",
    "/assets/images/words/panda.jpg",
    "/assets/images/words/parents.jpg",
    "/assets/images/words/parrot.jpg",
    "/assets/images/words/pencil.jpg",
    "/assets/images/words/pizza.jpg",
    "/assets/images/words/play.jpg",
    "/assets/images/words/potato.jpg",
    "/assets/images/words/shake hands.jpg",
    "/assets/images/words/shake_hands.jpg",
    "/assets/images/words/sister.jpg",
    "/assets/images/words/sit down.jpg",
    "/assets/images/words/sky.jpg",
    "/assets/images/words/snake.jpg",
    "/assets/images/words/spider.jpg",
    "/assets/images/words/spoon.jpg",
    "/assets/images/words/stand up.jpg",
    "/assets/images/words/star.jpg",
    "/assets/images/words/sun.jpg",
    "/assets/images/words/table.jpg",
    "/assets/images/words/teacher.jpg",
    "/assets/images/words/three.jpg",
    "/assets/images/words/tiger.jpg",
    "/assets/images/words/tomato.jpg",
    "/assets/images/words/tree.jpg",
    "/assets/images/words/two.jpg",
    "/css/style.css",
    "/games/prep-1/index.html",
    "/games/prep-1/unit1/Lesson 1 - Fruit Slicer.html",
    "/games/prep-1/unit1/Lesson 2 - Whack-A-Mole.html",
    "/games/prep-1/unit1/Lesson 3 - Safe Cracker.html",
    "/games/prep-1/unit1/Lesson 4 - Code Breaker.html",
    "/games/prep-1/unit1/Lesson 5 - Jigsaw Puzzle.html",
    "/games/prep-1/unit1/Lesson 6 - Court Judge.html",
    "/games/prep-1/unit2/Lesson 1 - Dungeon Doors.html",
    "/games/prep-1/unit2/Lesson 2 - Magic Hat.html",
    "/games/prep-1/unit2/Lesson 3 - Piano Maestro.html",
    "/games/prep-1/unit2/Lesson 4 - Space Invaders.html",
    "/games/prep-1/unit2/Lesson 5 - Asteroid Defender.html",
    "/games/prep-1/unit2/Lesson 6 - Archery Target.html",
    "/games/prep-1/unit3/Lesson 1 - Ghost Hunter.html",
    "/games/prep-1/unit3/Lesson 2 - UFO Abduction.html",
    "/games/prep-1/unit3/Lesson 3 - Cowboy Duel.html",
    "/games/prep-1/unit3/Lesson 4 - Firefighter.html",
    "/games/prep-1/unit3/Lesson 5 - Basketball Hoop.html",
    "/games/prep-1/unit3/Lesson 6 - Billiard Pool.html",
    "/games/prep-1/unit4/Lesson 1 - Burger Chef.html",
    "/games/prep-1/unit4/Lesson 2 - Potion Brewer.html",
    "/games/prep-1/unit4/Lesson 3 - Meteor Shower.html",
    "/games/prep-1/unit4/Lesson 4 - Fishing Pro.html",
    "/games/prep-1/unit4/Lesson 5 - Crane Claw.html",
    "/games/prep-1/unit4/Lesson 6 - Jungle Swing.html",
    "/games/prep-1/unit5/Lesson 1 - Factory Assembly.html",
    "/games/prep-1/unit5/Lesson 2 - Snowboard.html",
    "/games/prep-1/unit5/Lesson 3 - Hot Air Balloon.html",
    "/games/prep-1/unit5/Lesson 4 - Car Racing.html",
    "/games/prep-1/unit5/Lesson 5 - Minecart Tracks.html",
    "/games/prep-1/unit5/Lesson 6 - Submarine Dive.html",
    "/games/prep-1/unit6/Lesson 1 - Space Moon Lander.html",
    "/games/prep-1/unit6/Lesson 2 - Frogger Crossing.html",
    "/games/prep-1/unit6/Lesson 3 - Traffic Cop.html",
    "/games/prep-1/unit6/Lesson 4 - Bowling Alley.html",
    "/games/prep-1/unit6/Lesson 5 - Hurdle Race.html",
    "/games/prep-1/unit6/Lesson 6 - Pyramid Explorer.html",
    "/games/prep-2/unit1/Lesson1_CannonBlast.html",
    "/games/prep-2/unit1/Lesson2_BowArrow.html",
    "/games/prep-2/unit1/Lesson3_SpaceShooter.html",
    "/games/prep-2/unit1/Lesson4_Fishing.html",
    "/games/prep-2/unit1/Lesson5_BubblePopper.html",
    "/games/prep-2/unit1/Lesson6_WhackMole.html",
    "/games/prep-2/unit2/Lesson1_NinjaSlash.html",
    "/games/prep-2/unit2/Lesson2_ZombieDefense.html",
    "/games/prep-2/unit2/Lesson3_Basketball.html",
    "/games/prep-2/unit2/Lesson4_Minecart.html",
    "/games/prep-2/unit2/Lesson5_Darts.html",
    "/games/prep-2/unit2/Lesson6_UFO.html",
    "/games/prep-2/unit3/Lesson1_Bowling.html",
    "/games/prep-2/unit3/Lesson2_Pirate.html",
    "/games/prep-2/unit3/Lesson3_Frog.html",
    "/games/prep-2/unit3/Lesson4_Meteor.html",
    "/games/prep-2/unit3/Lesson5_Slingshot.html",
    "/games/prep-2/unit3/Lesson6_Soccer.html",
    "/games/prep-2/unit4/Lesson1_Submarine.html",
    "/games/prep-2/unit4/Lesson2_Helicopter.html",
    "/games/prep-2/unit4/Lesson3_Ghost.html",
    "/games/prep-2/unit4/Lesson4_Tank.html",
    "/games/prep-2/unit4/Lesson5_Spider.html",
    "/games/prep-2/unit4/Lesson6_Golf.html",
    "/games/prep-2/unit5/Lesson1_Trapdoor.html",
    "/games/prep-2/unit5/Lesson2_Train.html",
    "/games/prep-2/unit5/Lesson3_Cowboy.html",
    "/games/prep-2/unit5/Lesson4_Farm.html",
    "/games/prep-2/unit5/Lesson5_Reveal.html",
    "/games/prep-2/unit5/Lesson6_Pool.html",
    "/games/prep-2/unit6/Lesson1_UFO.html",
    "/games/prep-2/unit6/Lesson2_Race.html",
    "/games/prep-2/unit6/Lesson3_Shuriken.html",
    "/games/prep-2/unit6/Lesson4_Volcano.html",
    "/games/prep-2/unit6/Lesson5_Boomerang.html",
    "/games/prep-2/unit6/Lesson6_Lightning.html",
    "/games/primary-1/unit1/احمي القلعة.html",
    "/games/primary-1/unit1/التهجئة الذكية.html",
    "/games/primary-1/unit1/السباق الثلاثي.html",
    "/games/primary-1/unit1/المبارزة المزدوجة.html",
    "/games/primary-1/unit1/تحدي الاستماع.html",
    "/games/primary-1/unit1/تحدي السرعه.html",
    "/games/primary-1/unit1/خمن واكسب.html",
    "/games/primary-1/unit1/رتب واكسب.html",
    "/games/primary-1/unit1/سقوط الصور.html",
    "/games/primary-1/unit1/شد الحبل المعرفي.html",
    "/games/primary-1/unit1/شد الحبل.html",
    "/games/primary-1/unit1/صائد الكلمات.html",
    "/games/primary-1/unit1/عجلة الحظ.html",
    "/games/primary-1/unit1/غزو الفضاء.html",
    "/games/primary-1/unit1/كشاف الظلام.html",
    "/games/primary-1/unit1/لعبة الذاكرة.html",
    "/games/primary-1/unit2/القفز على الصخور.html",
    "/games/primary-1/unit2/بطاقات الذاكرة.html",
    "/games/primary-1/unit2/بناء البرج.html",
    "/games/primary-1/unit2/بناء الجمل.html",
    "/games/primary-1/unit2/تطابق الظل.html",
    "/games/primary-1/unit2/توصيل الجمل.html",
    "/games/primary-1/unit2/توصيل الكلمات.html",
    "/games/primary-1/unit2/حارس المرمى.html",
    "/games/primary-1/unit2/سؤال وجواب.html",
    "/games/primary-1/unit2/سقوط الكلمات.html",
    "/games/primary-1/unit2/صيد الكلمات.html",
    "/games/primary-1/unit2/قطار الكلمات.html",
    "/games/primary-1/unit2/لوحة التلوين.html",
    "/games/primary-1/unit2/مدفع الكلمات.html",
    "/games/primary-1/unit3/10_الاستماع_والاختيار.html",
    "/games/primary-1/unit3/11_بناء_الجمل.html",
    "/games/primary-1/unit3/12_بناء_البرج.html",
    "/games/primary-1/unit3/13_سباق_السيارات.html",
    "/games/primary-1/unit3/14_القطار_السريع.html",
    "/games/primary-1/unit3/15_صائد_الفراشات.html",
    "/games/primary-1/unit3/16_كرة_السلة.html",
    "/games/primary-1/unit3/17_البالون_الطائر.html",
    "/games/primary-1/unit3/18_توصيل_الظل.html",
    "/games/primary-1/unit3/19_صيد_البط.html",
    "/games/primary-1/unit3/1_صيد_الكلمات.html",
    "/games/primary-1/unit3/20_السمكة_الجائعة.html",
    "/games/primary-1/unit3/2_البطاقات_التعليمية.html",
    "/games/primary-1/unit3/3_توصيل_الكلمات.html",
    "/games/primary-1/unit3/4_سؤال_وجواب.html",
    "/games/primary-1/unit3/6_فرقعة_الفقاعات.html",
    "/games/primary-1/unit3/7_الحرف_المفقود.html",
    "/games/primary-1/unit3/8_تصنيف_الكلمات.html",
    "/games/primary-1/unit3/9_ذاكرة_البطاقات.html",
    "/games/primary-1/unit4/10_تلوين_الكلمات.html",
    "/games/primary-1/unit4/11_مطابقة_الظل.html",
    "/games/primary-1/unit4/12_صندوق_المفاجآت.html",
    "/games/primary-1/unit4/13_قطار_الكلمات.html",
    "/games/primary-1/unit4/14_الذاكرة_الخفية.html",
    "/games/primary-1/unit4/15_بالونات_الكلمات.html",
    "/games/primary-1/unit4/16_لعبة_الغميضة.html",
    "/games/primary-1/unit4/17_طائرة_الكلمات.html",
    "/games/primary-1/unit4/18_متاهة_الحروف.html",
    "/games/primary-1/unit4/19_عجلة_الحظ.html",
    "/games/primary-1/unit4/1_طبيب_العيون.html",
    "/games/primary-1/unit4/20_صياد_الكنوز.html",
    "/games/primary-1/unit4/21_الميزان_السحري.html",
    "/games/primary-1/unit4/22_توصيل_البطاقات.html",
    "/games/primary-1/unit4/23_لغز_الكلمات.html",
    "/games/primary-1/unit4/24_سباق_السيارات.html",
    "/games/primary-1/unit4/2_حديقة_الحيوان.html",
    "/games/primary-1/unit4/3_تحدي_الحواس_الخمس.html",
    "/games/primary-1/unit4/4_روبوت_الكلمات.html",
    "/games/primary-1/unit4/5_مطبخ_الملك.html",
    "/games/primary-1/unit4/6_بناء_الجسم.html",
    "/games/primary-1/unit4/7_سباق_الصواريخ.html",
    "/games/primary-1/unit4/8_لعبة_الساحر.html",
    "/games/primary-1/unit4/9_صيد_الأسماك.html",
    "/games/primary-1/unit5/10_قفزة_الضفدع.html",
    "/games/primary-1/unit5/11_الغواصة.html",
    "/games/primary-1/unit5/12_سفينة_الفضاء.html",
    "/games/primary-1/unit5/13_تجميع_الروبوت.html",
    "/games/primary-1/unit5/14_سباق_التزلج.html",
    "/games/primary-1/unit5/15_مزرعة_العد.html",
    "/games/primary-1/unit5/16_صندوق_الكنز.html",
    "/games/primary-1/unit5/17_الغيمة_الماطرة.html",
    "/games/primary-1/unit5/18_السلحفاة_السريعة.html",
    "/games/primary-1/unit5/19_البالونات_الطائرة.html",
    "/games/primary-1/unit5/1_صائد_الفقاعات.html",
    "/games/primary-1/unit5/20_مصنع_الحلوى.html",
    "/games/primary-1/unit5/21_إطعام_الديناصور.html",
    "/games/primary-1/unit5/22_وصفة_الساحرة.html",
    "/games/primary-1/unit5/23_الجسر_المتحرك.html",
    "/games/primary-1/unit5/24_سباق_السيارات.html",
    "/games/primary-1/unit5/25_كعكة_عيد_الميلاد.html",
    "/games/primary-1/unit5/2_القفز_فوق_المنصات.html",
    "/games/primary-1/unit5/3_السلة_السحرية.html",
    "/games/primary-1/unit5/4_قطف_الثمار.html",
    "/games/primary-1/unit5/5_ترتيب_القطار.html",
    "/games/primary-1/unit5/6_النينجا.html",
    "/games/primary-1/unit5/7_بائع_الآيس_كريم.html",
    "/games/primary-1/unit5/8_تسلق_الشجرة.html",
    "/games/primary-1/unit5/9_إطعام_الحيوانات.html",
    "/games/primary-1/unit5/index.html",
    "/games/primary-1/unit6/10_صيد_السمك.html",
    "/games/primary-1/unit6/11_خزانة_الملابس.html",
    "/games/primary-1/unit6/12_مطعم_الحروف.html",
    "/games/primary-1/unit6/14_البولينج.html",
    "/games/primary-1/unit6/15_الرماية.html",
    "/games/primary-1/unit6/16_فقاعات_الصابون.html",
    "/games/primary-1/unit6/17_السائق_المحترف.html",
    "/games/primary-1/unit6/18_النحلة_العاملة.html",
    "/games/primary-1/unit6/19_بناء_البرج.html",
    "/games/primary-1/unit6/1_إنقاذ_الحيوانات.html",
    "/games/primary-1/unit6/20_متاهة_الجبنة.html",
    "/games/primary-1/unit6/21_القفز_بالمظلة.html",
    "/games/primary-1/unit6/23_قطار_الحروف.html",
    "/games/primary-1/unit6/24_الحصالة.html",
    "/games/primary-1/unit6/25_صانع_الشطائر.html",
    "/games/primary-1/unit6/2_حديقة_الحيوان.html",
    "/games/primary-1/unit6/3_التزلج_على_الجليد.html",
    "/games/primary-1/unit6/4_رمي_السهام.html",
    "/games/primary-1/unit6/5_كشف_المصباح.html",
    "/games/primary-1/unit6/7_مصنع_العصائر.html",
    "/games/primary-1/unit6/8_رحلة_المنطاد.html",
    "/games/primary-1/unit6/9_سباق_الخيل.html",
    "/games/primary-1/unit6/index.html",
    "/games/primary-2/unit1/الدرس الاول - لعبة رمي السهام.html",
    "/games/primary-2/unit1/الدرس الثالث - لعبة فرقعة الفقاعات.html",
    "/games/primary-2/unit1/الدرس الثاني - لعبة سفن الفضاء.html",
    "/games/primary-2/unit1/الدرس الرابع - لعبة الثعبان.html",
    "/games/primary-2/unit2/الدرس الاول - لعبة البالونات.html",
    "/games/primary-2/unit2/الدرس الثالث - لعبة ضرب الخلد.html",
    "/games/primary-2/unit2/الدرس الثاني - لعبة صيد الاسماك.html",
    "/games/primary-2/unit2/الدرس الثاني - لعبة صيد السمك.html",
    "/games/primary-2/unit2/الدرس الرابع - لعبة سباق السيارات.html",
    "/games/primary-2/unit3/الدرس الاول - لعبة القفز.html",
    "/games/primary-2/unit3/الدرس الاول - لعبة قفز الكواكب.html",
    "/games/primary-2/unit3/الدرس الثالث - لعبة فك الشفرة.html",
    "/games/primary-2/unit3/الدرس الثاني - لعبة تكسير الثلج.html",
    "/games/primary-2/unit3/الدرس الرابع - لعبة الجري.html",
    "/games/primary-2/unit3/الدرس الرابع - لعبة الركض السريع.html",
    "/games/primary-2/unit4/الدرس الاول - لعبة معركة الزعيم.html",
    "/games/primary-2/unit4/الدرس الثالث - لعبة المتاهة.html",
    "/games/primary-2/unit4/الدرس الثاني - لعبة قنابل الالوان.html",
    "/games/primary-2/unit4/الدرس الثاني - لعبة قنبلة الالوان.html",
    "/games/primary-2/unit4/الدرس الرابع - لعبة العجلة الدوارة.html",
    "/games/primary-2/unit5/الدرس الاول - لعبة تطابق الظلال.html",
    "/games/primary-2/unit5/الدرس الاول - لعبة مطابقة الظل.html",
    "/games/primary-2/unit5/الدرس الثالث - لعبة البرق السريعة.html",
    "/games/primary-2/unit5/الدرس الثالث - لعبة البرق.html",
    "/games/primary-2/unit5/الدرس الثاني - لعبة الترتيب.html",
    "/games/primary-2/unit5/الدرس الثاني - لعبة تجميع الكلمات.html",
    "/games/primary-2/unit5/الدرس الرابع - لعبة الهروب من الحمم.html",
    "/games/primary-2/unit6/الدرس الاول - لعبة القناص.html",
    "/games/primary-2/unit6/الدرس الثالث - لعبة تشكيل الكلمات.html",
    "/games/primary-2/unit6/الدرس الثالث - لعبة مصنع الكلمات.html",
    "/games/primary-2/unit6/الدرس الثاني - لعبة انفجار السديم.html",
    "/games/primary-2/unit6/الدرس الرابع - لعبة صيد الكلمات.html",
    "/games/primary-3/unit1/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit1/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit1/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit1/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit2/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit2/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit2/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit2/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit3/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit3/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit3/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit3/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit4/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit4/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit4/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit4/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit5/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit5/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit5/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit5/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit6/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit6/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit6/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit6/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit1/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit1/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit1/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit1/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit2/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit2/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit2/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit2/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit3/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit3/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit3/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit3/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit4/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit4/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit4/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit4/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit5/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit5/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit5/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit5/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit6/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit6/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit6/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit6/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit1/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit1/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit1/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit1/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit2/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit2/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit2/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit2/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit3/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit3/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit3/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit3/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit4/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit4/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit4/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit4/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit5/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit5/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit5/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit5/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit6/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit6/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit6/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit6/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit1/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit1/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit1/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit1/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit2/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit2/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit2/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit2/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit3/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit3/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit3/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit3/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit4/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit4/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit4/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit4/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit5/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit5/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit5/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit5/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit6/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit6/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit6/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit6/Lesson 4 - Word Snake.html",
    "/images/clean_bg.png",
    "/images/dashboard_bg.png",
    "/images/game_icon_1.png",
    "/images/game_icon_2.png",
    "/images/game_icon_3.png",
    "/images/game_icon_4.png",
    "/images/login_bg.png",
    "/images/logo_icon.png",
    "/images/pixar_bg.png",
    "/images/prep_1.png",
    "/images/prep_2.png",
    "/images/prep_3.png",
    "/images/primary_1.png",
    "/images/primary_2.png",
    "/images/primary_3.png",
    "/images/primary_4.png",
    "/images/primary_5.png",
    "/images/primary_6.png",
    "/js/auth.js",
    "/js/data.js",
    "/js/game-enhancements.js"
];

// Always add core pages to cache as well
const corePages = [
  '/',
  '/index.html',
  '/dashboard.html',
  '/grade.html',
  '/admin.html',
  '/unit.html'
];
urlsToCache.push(...corePages);

self.addEventListener('install', event => {
    // Force immediate installation
    self.skipWaiting();
    
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                console.log('Opened cache, starting massive download...');
                return Promise.all(
                    urlsToCache.map(url => {
                        return cache.add(url).catch(err => {
                            console.warn('Failed to cache:', url, err);
                        });
                    })
                );
            })
    );
});

self.addEventListener('activate', event => {
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames.map(cacheName => {
                    if (cacheName !== CACHE_NAME) {
                        console.log('Deleting old cache:', cacheName);
                        return caches.delete(cacheName);
                    }
                })
            );
        }).then(() => self.clients.claim())
    );
});

self.addEventListener('fetch', event => {
    event.respondWith(
        caches.match(event.request)
            .then(response => {
                // Cache hit - return response
                if (response) {
                    return response;
                }
                
                // Fallback to network
                return fetch(event.request).catch(err => {
                    console.log('Offline and not cached:', event.request.url);
                });
            })
    );
});
