const CACHE_NAME = 'english-toon-v20260724203543';
const urlsToCache = [
    "/",
    "/.gitattributes",
    "/admin.html",
    "/books.html",
    "/check_images.py",
    "/dashboard.html",
    "/exams.html",
    "/fix-alert.py",
    "/fix-arabic.js",
    "/fix-arabic.ps1",
    "/fix-arabic.py",
    "/fix-html-encoding.py",
    "/fix-meta.py",
    "/games.html",
    "/games_map.json",
    "/generate-3d-assets-v2.ps1",
    "/generate-3d-assets.ps1",
    "/grade.html",
    "/import-games.py",
    "/import-prep2.py",
    "/import_games.js",
    "/import_games.ps1",
    "/index.html",
    "/inject-enhancements.py",
    "/inject_emojis.ps1",
    "/inject_enhancements.ps1",
    "/inject_sentences.ps1",
    "/interactive-books.html",
    "/migrate-games.ps1",
    "/migrate-games.py",
    "/pdf-files.html",
    "/protect_games.ps1",
    "/README.md",
    "/regenerate_json.ps1",
    "/test-bytes.py",
    "/test-decode.py",
    "/test_apple.jpg",
    "/unit.html",
    "/assets/images/cover.jpg",
    "/assets/images/cover_2027.jpg",
    "/assets/images/prim2_pages/page_1.jpg",
    "/assets/images/prim2_pages/page_10.jpg",
    "/assets/images/prim2_pages/page_11.jpg",
    "/assets/images/prim2_pages/page_12.jpg",
    "/assets/images/prim2_pages/page_13.jpg",
    "/assets/images/prim2_pages/page_14.jpg",
    "/assets/images/prim2_pages/page_15.jpg",
    "/assets/images/prim2_pages/page_16.jpg",
    "/assets/images/prim2_pages/page_17.jpg",
    "/assets/images/prim2_pages/page_18.jpg",
    "/assets/images/prim2_pages/page_19.jpg",
    "/assets/images/prim2_pages/page_2.jpg",
    "/assets/images/prim2_pages/page_20.jpg",
    "/assets/images/prim2_pages/page_21.jpg",
    "/assets/images/prim2_pages/page_22.jpg",
    "/assets/images/prim2_pages/page_23.jpg",
    "/assets/images/prim2_pages/page_24.jpg",
    "/assets/images/prim2_pages/page_25.jpg",
    "/assets/images/prim2_pages/page_26.jpg",
    "/assets/images/prim2_pages/page_27.jpg",
    "/assets/images/prim2_pages/page_28.jpg",
    "/assets/images/prim2_pages/page_29.jpg",
    "/assets/images/prim2_pages/page_3.jpg",
    "/assets/images/prim2_pages/page_30.jpg",
    "/assets/images/prim2_pages/page_31.jpg",
    "/assets/images/prim2_pages/page_32.jpg",
    "/assets/images/prim2_pages/page_33.jpg",
    "/assets/images/prim2_pages/page_34.jpg",
    "/assets/images/prim2_pages/page_35.jpg",
    "/assets/images/prim2_pages/page_36.jpg",
    "/assets/images/prim2_pages/page_37.jpg",
    "/assets/images/prim2_pages/page_38.jpg",
    "/assets/images/prim2_pages/page_39.jpg",
    "/assets/images/prim2_pages/page_4.jpg",
    "/assets/images/prim2_pages/page_40.jpg",
    "/assets/images/prim2_pages/page_41.jpg",
    "/assets/images/prim2_pages/page_42.jpg",
    "/assets/images/prim2_pages/page_43.jpg",
    "/assets/images/prim2_pages/page_44.jpg",
    "/assets/images/prim2_pages/page_45.jpg",
    "/assets/images/prim2_pages/page_46.jpg",
    "/assets/images/prim2_pages/page_47.jpg",
    "/assets/images/prim2_pages/page_48.jpg",
    "/assets/images/prim2_pages/page_49.jpg",
    "/assets/images/prim2_pages/page_5.jpg",
    "/assets/images/prim2_pages/page_50.jpg",
    "/assets/images/prim2_pages/page_51.jpg",
    "/assets/images/prim2_pages/page_52.jpg",
    "/assets/images/prim2_pages/page_53.jpg",
    "/assets/images/prim2_pages/page_54.jpg",
    "/assets/images/prim2_pages/page_55.jpg",
    "/assets/images/prim2_pages/page_56.jpg",
    "/assets/images/prim2_pages/page_57.jpg",
    "/assets/images/prim2_pages/page_58.jpg",
    "/assets/images/prim2_pages/page_59.jpg",
    "/assets/images/prim2_pages/page_6.jpg",
    "/assets/images/prim2_pages/page_60.jpg",
    "/assets/images/prim2_pages/page_61.jpg",
    "/assets/images/prim2_pages/page_62.jpg",
    "/assets/images/prim2_pages/page_63.jpg",
    "/assets/images/prim2_pages/page_64.jpg",
    "/assets/images/prim2_pages/page_65.jpg",
    "/assets/images/prim2_pages/page_66.jpg",
    "/assets/images/prim2_pages/page_67.jpg",
    "/assets/images/prim2_pages/page_68.jpg",
    "/assets/images/prim2_pages/page_69.jpg",
    "/assets/images/prim2_pages/page_7.jpg",
    "/assets/images/prim2_pages/page_70.jpg",
    "/assets/images/prim2_pages/page_71.jpg",
    "/assets/images/prim2_pages/page_72.jpg",
    "/assets/images/prim2_pages/page_8.jpg",
    "/assets/images/prim2_pages/page_9.jpg",
    "/assets/images/words/ant.jpg",
    "/assets/images/words/apple.jpg",
    "/assets/images/words/arm.jpg",
    "/assets/images/words/arrow.jpg",
    "/assets/images/words/axe.jpg",
    "/assets/images/words/bag.jpg",
    "/assets/images/words/bee.jpg",
    "/assets/images/words/bird.jpg",
    "/assets/images/words/blue.jpg",
    "/assets/images/words/board.jpg",
    "/assets/images/words/book.jpg",
    "/assets/images/words/brother.jpg",
    "/assets/images/words/bus.jpg",
    "/assets/images/words/butterfly.jpg",
    "/assets/images/words/chair.jpg",
    "/assets/images/words/desk.jpg",
    "/assets/images/words/dog.jpg",
    "/assets/images/words/doll.jpg",
    "/assets/images/words/door.jpg",
    "/assets/images/words/drum.jpg",
    "/assets/images/words/duck.jpg",
    "/assets/images/words/father.jpg",
    "/assets/images/words/five.jpg",
    "/assets/images/words/flower.jpg",
    "/assets/images/words/flowers.jpg",
    "/assets/images/words/four.jpg",
    "/assets/images/words/Goodbye.jpg",
    "/assets/images/words/grandfather.jpg",
    "/assets/images/words/grandmother.jpg",
    "/assets/images/words/grass.jpg",
    "/assets/images/words/hair.jpg",
    "/assets/images/words/hana.jpg",
    "/assets/images/words/hands.jpg",
    "/assets/images/words/hany.jpg",
    "/assets/images/words/hat.jpg",
    "/assets/images/words/Hello.jpg",
    "/assets/images/words/horse.jpg",
    "/assets/images/words/house.jpg",
    "/assets/images/words/ill.jpg",
    "/assets/images/words/in.jpg",
    "/assets/images/words/ink.jpg",
    "/assets/images/words/insect.jpg",
    "/assets/images/words/miss_mona.jpg",
    "/assets/images/words/mother.jpg",
    "/assets/images/words/nail.jpg",
    "/assets/images/words/neck.jpg",
    "/assets/images/words/net.jpg",
    "/assets/images/words/nose.jpg",
    "/assets/images/words/nurse.jpg",
    "/assets/images/words/one.jpg",
    "/assets/images/words/open your books.jpg",
    "/assets/images/words/panda.jpg",
    "/assets/images/words/parents.jpg",
    "/assets/images/words/parrot.jpg",
    "/assets/images/words/pencil.jpg",
    "/assets/images/words/pizza.jpg",
    "/assets/images/words/play.jpg",
    "/assets/images/words/potato.jpg",
    "/assets/images/words/shake hands.jpg",
    "/assets/images/words/shake_hands.jpg",
    "/assets/images/words/sister.jpg",
    "/assets/images/words/sit down.jpg",
    "/assets/images/words/sky.jpg",
    "/assets/images/words/snake.jpg",
    "/assets/images/words/spider.jpg",
    "/assets/images/words/spoon.jpg",
    "/assets/images/words/stand up.jpg",
    "/assets/images/words/star.jpg",
    "/assets/images/words/sun.jpg",
    "/assets/images/words/table.jpg",
    "/assets/images/words/teacher.jpg",
    "/assets/images/words/three.jpg",
    "/assets/images/words/tiger.jpg",
    "/assets/images/words/tomato.jpg",
    "/assets/images/words/tree.jpg",
    "/assets/images/words/two.jpg",
    "/css/p1_interactive_styles.css",
    "/css/style.css",
    "/games/prep-1/index.html",
    "/games/prep-1/unit1/G1_cannon.html",
    "/games/prep-1/unit1/G1_fishing.html",
    "/games/prep-1/unit1/G2_arrow.html",
    "/games/prep-1/unit1/G2_cannon.html",
    "/games/prep-1/unit1/G3_balloon.html",
    "/games/prep-1/unit1/G3_fishing.html",
    "/games/prep-1/unit1/G4_spaceship.html",
    "/games/prep-1/unit1/G5_archery.html",
    "/games/prep-1/unit1/G5_shuriken.html",
    "/games/prep-1/unit1/Lesson 1 - Fruit Slicer.html",
    "/games/prep-1/unit1/Lesson 2 - Whack-A-Mole.html",
    "/games/prep-1/unit1/Lesson 3 - Safe Cracker.html",
    "/games/prep-1/unit1/Lesson 4 - Code Breaker.html",
    "/games/prep-1/unit1/Lesson 5 - Jigsaw Puzzle.html",
    "/games/prep-1/unit1/Lesson 6 - Court Judge.html",
    "/games/prep-1/unit2/G10_spider.html",
    "/games/prep-1/unit2/G1_fishing.html",
    "/games/prep-1/unit2/G2_cannon.html",
    "/games/prep-1/unit2/G3_balloon.html",
    "/games/prep-1/unit2/G4_spaceship.html",
    "/games/prep-1/unit2/G5_archery.html",
    "/games/prep-1/unit2/G6_bowling.html",
    "/games/prep-1/unit2/G7_soccer.html",
    "/games/prep-1/unit2/G8_basketball.html",
    "/games/prep-1/unit2/G9_boomerang.html",
    "/games/prep-1/unit2/Lesson 1 - Dungeon Doors.html",
    "/games/prep-1/unit2/Lesson 2 - Magic Hat.html",
    "/games/prep-1/unit2/Lesson 3 - Piano Maestro.html",
    "/games/prep-1/unit2/Lesson 4 - Space Invaders.html",
    "/games/prep-1/unit2/Lesson 5 - Asteroid Defender.html",
    "/games/prep-1/unit2/Lesson 6 - Archery Target.html",
    "/games/prep-1/unit3/G11_helicopter.html",
    "/games/prep-1/unit3/G12_lightning.html",
    "/games/prep-1/unit3/G13_volcano.html",
    "/games/prep-1/unit3/G14_tank.html",
    "/games/prep-1/unit3/G15_train.html",
    "/games/prep-1/unit3/G1_fishing.html",
    "/games/prep-1/unit3/G2_cannon.html",
    "/games/prep-1/unit3/G3_balloon.html",
    "/games/prep-1/unit3/G4_spaceship.html",
    "/games/prep-1/unit3/G5_archery.html",
    "/games/prep-1/unit3/Lesson 1 - Ghost Hunter.html",
    "/games/prep-1/unit3/Lesson 2 - UFO Abduction.html",
    "/games/prep-1/unit3/Lesson 3 - Cowboy Duel.html",
    "/games/prep-1/unit3/Lesson 4 - Firefighter.html",
    "/games/prep-1/unit3/Lesson 5 - Basketball Hoop.html",
    "/games/prep-1/unit3/Lesson 6 - Billiard Pool.html",
    "/games/prep-1/unit4/G16_lasso.html",
    "/games/prep-1/unit4/G17_wand.html",
    "/games/prep-1/unit4/G18_billiard.html",
    "/games/prep-1/unit4/G19_ufo.html",
    "/games/prep-1/unit4/G1_fishing.html",
    "/games/prep-1/unit4/G20_trapdoor.html",
    "/games/prep-1/unit4/G2_cannon.html",
    "/games/prep-1/unit4/G3_balloon.html",
    "/games/prep-1/unit4/G4_spaceship.html",
    "/games/prep-1/unit4/G5_archery.html",
    "/games/prep-1/unit4/Lesson 1 - Burger Chef.html",
    "/games/prep-1/unit4/Lesson 2 - Potion Brewer.html",
    "/games/prep-1/unit4/Lesson 3 - Meteor Shower.html",
    "/games/prep-1/unit4/Lesson 4 - Fishing Pro.html",
    "/games/prep-1/unit4/Lesson 5 - Crane Claw.html",
    "/games/prep-1/unit4/Lesson 6 - Jungle Swing.html",
    "/games/prep-1/unit5/G1_fishing.html",
    "/games/prep-1/unit5/G21_racecar.html",
    "/games/prep-1/unit5/G22_water.html",
    "/games/prep-1/unit5/G23_dart.html",
    "/games/prep-1/unit5/G24_slingshot.html",
    "/games/prep-1/unit5/G25_whack.html",
    "/games/prep-1/unit5/G2_cannon.html",
    "/games/prep-1/unit5/G3_balloon.html",
    "/games/prep-1/unit5/G4_spaceship.html",
    "/games/prep-1/unit5/G5_archery.html",
    "/games/prep-1/unit5/Lesson 1 - Factory Assembly.html",
    "/games/prep-1/unit5/Lesson 2 - Snowboard.html",
    "/games/prep-1/unit5/Lesson 3 - Hot Air Balloon.html",
    "/games/prep-1/unit5/Lesson 4 - Car Racing.html",
    "/games/prep-1/unit5/Lesson 5 - Minecart Tracks.html",
    "/games/prep-1/unit5/Lesson 6 - Submarine Dive.html",
    "/games/prep-1/unit6/G1_fishing.html",
    "/games/prep-1/unit6/G26_balloon.html",
    "/games/prep-1/unit6/G27_boxing.html",
    "/games/prep-1/unit6/G28_paperplane.html",
    "/games/prep-1/unit6/G29_goldminer.html",
    "/games/prep-1/unit6/G2_cannon.html",
    "/games/prep-1/unit6/G30_catapult.html",
    "/games/prep-1/unit6/G3_balloon.html",
    "/games/prep-1/unit6/G4_spaceship.html",
    "/games/prep-1/unit6/G5_archery.html",
    "/games/prep-1/unit6/Lesson 1 - Space Moon Lander.html",
    "/games/prep-1/unit6/Lesson 2 - Frogger Crossing.html",
    "/games/prep-1/unit6/Lesson 3 - Traffic Cop.html",
    "/games/prep-1/unit6/Lesson 4 - Bowling Alley.html",
    "/games/prep-1/unit6/Lesson 5 - Hurdle Race.html",
    "/games/prep-1/unit6/Lesson 6 - Pyramid Explorer.html",
    "/games/prep-2/unit1/G1_cannon.html",
    "/games/prep-2/unit1/G1_fishing.html",
    "/games/prep-2/unit1/G2_arrow.html",
    "/games/prep-2/unit1/G2_cannon.html",
    "/games/prep-2/unit1/G3_balloon.html",
    "/games/prep-2/unit1/G3_fishing.html",
    "/games/prep-2/unit1/G4_spaceship.html",
    "/games/prep-2/unit1/G5_archery.html",
    "/games/prep-2/unit1/G5_shuriken.html",
    "/games/prep-2/unit1/Lesson1_CannonBlast.html",
    "/games/prep-2/unit1/Lesson2_BowArrow.html",
    "/games/prep-2/unit1/Lesson3_SpaceShooter.html",
    "/games/prep-2/unit1/Lesson4_Fishing.html",
    "/games/prep-2/unit1/Lesson5_BubblePopper.html",
    "/games/prep-2/unit1/Lesson6_WhackMole.html",
    "/games/prep-2/unit2/G10_spider.html",
    "/games/prep-2/unit2/G1_fishing.html",
    "/games/prep-2/unit2/G2_cannon.html",
    "/games/prep-2/unit2/G3_balloon.html",
    "/games/prep-2/unit2/G4_spaceship.html",
    "/games/prep-2/unit2/G5_archery.html",
    "/games/prep-2/unit2/G6_bowling.html",
    "/games/prep-2/unit2/G7_soccer.html",
    "/games/prep-2/unit2/G8_basketball.html",
    "/games/prep-2/unit2/G9_boomerang.html",
    "/games/prep-2/unit2/Lesson1_NinjaSlash.html",
    "/games/prep-2/unit2/Lesson2_ZombieDefense.html",
    "/games/prep-2/unit2/Lesson3_Basketball.html",
    "/games/prep-2/unit2/Lesson4_Minecart.html",
    "/games/prep-2/unit2/Lesson5_Darts.html",
    "/games/prep-2/unit2/Lesson6_UFO.html",
    "/games/prep-2/unit3/G11_helicopter.html",
    "/games/prep-2/unit3/G12_lightning.html",
    "/games/prep-2/unit3/G13_volcano.html",
    "/games/prep-2/unit3/G14_tank.html",
    "/games/prep-2/unit3/G15_train.html",
    "/games/prep-2/unit3/G1_fishing.html",
    "/games/prep-2/unit3/G2_cannon.html",
    "/games/prep-2/unit3/G3_balloon.html",
    "/games/prep-2/unit3/G4_spaceship.html",
    "/games/prep-2/unit3/G5_archery.html",
    "/games/prep-2/unit3/Lesson1_Bowling.html",
    "/games/prep-2/unit3/Lesson2_Pirate.html",
    "/games/prep-2/unit3/Lesson3_Frog.html",
    "/games/prep-2/unit3/Lesson4_Meteor.html",
    "/games/prep-2/unit3/Lesson5_Slingshot.html",
    "/games/prep-2/unit3/Lesson6_Soccer.html",
    "/games/prep-2/unit4/G16_lasso.html",
    "/games/prep-2/unit4/G17_wand.html",
    "/games/prep-2/unit4/G18_billiard.html",
    "/games/prep-2/unit4/G19_ufo.html",
    "/games/prep-2/unit4/G1_fishing.html",
    "/games/prep-2/unit4/G20_trapdoor.html",
    "/games/prep-2/unit4/G2_cannon.html",
    "/games/prep-2/unit4/G3_balloon.html",
    "/games/prep-2/unit4/G4_spaceship.html",
    "/games/prep-2/unit4/G5_archery.html",
    "/games/prep-2/unit4/Lesson1_Submarine.html",
    "/games/prep-2/unit4/Lesson2_Helicopter.html",
    "/games/prep-2/unit4/Lesson3_Ghost.html",
    "/games/prep-2/unit4/Lesson4_Tank.html",
    "/games/prep-2/unit4/Lesson5_Spider.html",
    "/games/prep-2/unit4/Lesson6_Golf.html",
    "/games/prep-2/unit5/G1_fishing.html",
    "/games/prep-2/unit5/G21_racecar.html",
    "/games/prep-2/unit5/G22_water.html",
    "/games/prep-2/unit5/G23_dart.html",
    "/games/prep-2/unit5/G24_slingshot.html",
    "/games/prep-2/unit5/G25_whack.html",
    "/games/prep-2/unit5/G2_cannon.html",
    "/games/prep-2/unit5/G3_balloon.html",
    "/games/prep-2/unit5/G4_spaceship.html",
    "/games/prep-2/unit5/G5_archery.html",
    "/games/prep-2/unit5/Lesson1_Trapdoor.html",
    "/games/prep-2/unit5/Lesson2_Train.html",
    "/games/prep-2/unit5/Lesson3_Cowboy.html",
    "/games/prep-2/unit5/Lesson4_Farm.html",
    "/games/prep-2/unit5/Lesson5_Reveal.html",
    "/games/prep-2/unit5/Lesson6_Pool.html",
    "/games/prep-2/unit6/G1_fishing.html",
    "/games/prep-2/unit6/G26_balloon.html",
    "/games/prep-2/unit6/G27_boxing.html",
    "/games/prep-2/unit6/G28_paperplane.html",
    "/games/prep-2/unit6/G29_goldminer.html",
    "/games/prep-2/unit6/G2_cannon.html",
    "/games/prep-2/unit6/G30_catapult.html",
    "/games/prep-2/unit6/G3_balloon.html",
    "/games/prep-2/unit6/G4_spaceship.html",
    "/games/prep-2/unit6/G5_archery.html",
    "/games/prep-2/unit6/Lesson1_UFO.html",
    "/games/prep-2/unit6/Lesson2_Race.html",
    "/games/prep-2/unit6/Lesson3_Shuriken.html",
    "/games/prep-2/unit6/Lesson4_Volcano.html",
    "/games/prep-2/unit6/Lesson5_Boomerang.html",
    "/games/prep-2/unit6/Lesson6_Lightning.html",
    "/games/prep-3/unit1/G1_cannon.html",
    "/games/prep-3/unit1/G1_fishing.html",
    "/games/prep-3/unit1/G2_arrow.html",
    "/games/prep-3/unit1/G2_cannon.html",
    "/games/prep-3/unit1/G3_balloon.html",
    "/games/prep-3/unit1/G3_fishing.html",
    "/games/prep-3/unit1/G4_spaceship.html",
    "/games/prep-3/unit1/G5_archery.html",
    "/games/prep-3/unit1/G5_shuriken.html",
    "/games/prep-3/unit1/L1_cannon_Beyond_My_Looks.html",
    "/games/prep-3/unit1/L2_arrow_Self_Discovery.html",
    "/games/prep-3/unit1/L3_fishing_The_Mirror_Moment.html",
    "/games/prep-3/unit1/L4_spaceship_Practice__Skills.html",
    "/games/prep-3/unit1/L5_shuriken_Lets_Talk.html",
    "/games/prep-3/unit1/L6_bowling_Practice__Skills.html",
    "/games/prep-3/unit2/G10_spider.html",
    "/games/prep-3/unit2/G1_fishing.html",
    "/games/prep-3/unit2/G2_cannon.html",
    "/games/prep-3/unit2/G3_balloon.html",
    "/games/prep-3/unit2/G4_spaceship.html",
    "/games/prep-3/unit2/G5_archery.html",
    "/games/prep-3/unit2/G6_bowling.html",
    "/games/prep-3/unit2/G7_soccer.html",
    "/games/prep-3/unit2/G8_basketball.html",
    "/games/prep-3/unit2/G9_boomerang.html",
    "/games/prep-3/unit2/L1_soccer_Stay_Connected.html",
    "/games/prep-3/unit2/L2_basketball_Challenges_and_Solutions.html",
    "/games/prep-3/unit2/L3_boomerang_The_Silent_Dinner.html",
    "/games/prep-3/unit2/L4_spider_Practice__Skills.html",
    "/games/prep-3/unit2/L5_helicopter_Practice__Skills.html",
    "/games/prep-3/unit2/L6_lightning_Practice__Skills.html",
    "/games/prep-3/unit3/G11_helicopter.html",
    "/games/prep-3/unit3/G12_lightning.html",
    "/games/prep-3/unit3/G13_volcano.html",
    "/games/prep-3/unit3/G14_tank.html",
    "/games/prep-3/unit3/G15_train.html",
    "/games/prep-3/unit3/G1_fishing.html",
    "/games/prep-3/unit3/G2_cannon.html",
    "/games/prep-3/unit3/G3_balloon.html",
    "/games/prep-3/unit3/G4_spaceship.html",
    "/games/prep-3/unit3/G5_archery.html",
    "/games/prep-3/unit3/L1_volcano_AI.html",
    "/games/prep-3/unit3/L2_tank_A_I_Technology.html",
    "/games/prep-3/unit3/L3_train_Robot_Teacher.html",
    "/games/prep-3/unit3/L4_lasso_Practice__Skills.html",
    "/games/prep-3/unit3/L5_wand_Smart_Robots.html",
    "/games/prep-3/unit3/L6_billiard_Practice__Skills.html",
    "/games/prep-3/unit4/G16_lasso.html",
    "/games/prep-3/unit4/G17_wand.html",
    "/games/prep-3/unit4/G18_billiard.html",
    "/games/prep-3/unit4/G19_ufo.html",
    "/games/prep-3/unit4/G1_fishing.html",
    "/games/prep-3/unit4/G20_trapdoor.html",
    "/games/prep-3/unit4/G2_cannon.html",
    "/games/prep-3/unit4/G3_balloon.html",
    "/games/prep-3/unit4/G4_spaceship.html",
    "/games/prep-3/unit4/G5_archery.html",
    "/games/prep-3/unit4/L1_ufo_Screen_Time.html",
    "/games/prep-3/unit4/L2_trapdoor_Egypts_Smart_Future.html",
    "/games/prep-3/unit4/L3_racecar_Balancing_Screen_Time.html",
    "/games/prep-3/unit4/L4_water_Story_Time.html",
    "/games/prep-3/unit4/L5_dart_Lets_Talk.html",
    "/games/prep-3/unit4/L6_slingshot_Practice__Skills.html",
    "/games/prep-3/unit5/G1_fishing.html",
    "/games/prep-3/unit5/G21_racecar.html",
    "/games/prep-3/unit5/G22_water.html",
    "/games/prep-3/unit5/G23_dart.html",
    "/games/prep-3/unit5/G24_slingshot.html",
    "/games/prep-3/unit5/G25_whack.html",
    "/games/prep-3/unit5/G2_cannon.html",
    "/games/prep-3/unit5/G3_balloon.html",
    "/games/prep-3/unit5/G4_spaceship.html",
    "/games/prep-3/unit5/G5_archery.html",
    "/games/prep-3/unit5/L1_whack_Think_like_a_Designer.html",
    "/games/prep-3/unit5/L2_balloon_Dream_It_Build_It.html",
    "/games/prep-3/unit5/L3_boxing_See_through_Their_Eyes.html",
    "/games/prep-3/unit5/L4_paperplane_Story_Time.html",
    "/games/prep-3/unit5/L5_goldminer_Lets_Talk.html",
    "/games/prep-3/unit5/L6_magnet_Practice__Skills.html",
    "/games/prep-3/unit6/G1_fishing.html",
    "/games/prep-3/unit6/G26_balloon.html",
    "/games/prep-3/unit6/G27_boxing.html",
    "/games/prep-3/unit6/G28_paperplane.html",
    "/games/prep-3/unit6/G29_goldminer.html",
    "/games/prep-3/unit6/G2_cannon.html",
    "/games/prep-3/unit6/G30_catapult.html",
    "/games/prep-3/unit6/G3_balloon.html",
    "/games/prep-3/unit6/G4_spaceship.html",
    "/games/prep-3/unit6/G5_archery.html",
    "/games/prep-3/unit6/L1_catapult_The_Power_of_Stories.html",
    "/games/prep-3/unit6/L2_pingpong_The_story_That_Helped_Me.html",
    "/games/prep-3/unit6/L3_diver_Elements_of_a_Story.html",
    "/games/prep-3/unit6/L4_parachute_Story_Time.html",
    "/games/prep-3/unit6/L5_karate_Lets_Talk.html",
    "/games/prep-3/unit6/L6_potion_My_Own_Story.html",
    "/games/primary-1/unit1/G1_cannon.html",
    "/games/primary-1/unit1/G1_fishing.html",
    "/games/primary-1/unit1/G2_arrow.html",
    "/games/primary-1/unit1/G2_cannon.html",
    "/games/primary-1/unit1/G3_balloon.html",
    "/games/primary-1/unit1/G3_fishing.html",
    "/games/primary-1/unit1/G4_spaceship.html",
    "/games/primary-1/unit1/G5_archery.html",
    "/games/primary-1/unit1/G5_shuriken.html",
    "/games/primary-1/unit1/احمي القلعة.html",
    "/games/primary-1/unit1/التهجئة الذكية.html",
    "/games/primary-1/unit1/السباق الثلاثي.html",
    "/games/primary-1/unit1/المبارزة المزدوجة.html",
    "/games/primary-1/unit1/تحدي الاستماع.html",
    "/games/primary-1/unit1/تحدي السرعه.html",
    "/games/primary-1/unit1/خمن واكسب.html",
    "/games/primary-1/unit1/رتب واكسب.html",
    "/games/primary-1/unit1/سقوط الصور.html",
    "/games/primary-1/unit1/شد الحبل المعرفي.html",
    "/games/primary-1/unit1/شد الحبل.html",
    "/games/primary-1/unit1/صائد الكلمات.html",
    "/games/primary-1/unit1/عجلة الحظ.html",
    "/games/primary-1/unit1/غزو الفضاء.html",
    "/games/primary-1/unit1/كشاف الظلام.html",
    "/games/primary-1/unit1/لعبة الذاكرة.html",
    "/games/primary-1/unit2/G10_spider.html",
    "/games/primary-1/unit2/G1_fishing.html",
    "/games/primary-1/unit2/G2_cannon.html",
    "/games/primary-1/unit2/G3_balloon.html",
    "/games/primary-1/unit2/G4_spaceship.html",
    "/games/primary-1/unit2/G5_archery.html",
    "/games/primary-1/unit2/G6_bowling.html",
    "/games/primary-1/unit2/G7_soccer.html",
    "/games/primary-1/unit2/G8_basketball.html",
    "/games/primary-1/unit2/G9_boomerang.html",
    "/games/primary-1/unit2/القفز على الصخور.html",
    "/games/primary-1/unit2/بطاقات الذاكرة.html",
    "/games/primary-1/unit2/بناء البرج.html",
    "/games/primary-1/unit2/بناء الجمل.html",
    "/games/primary-1/unit2/تطابق الظل.html",
    "/games/primary-1/unit2/توصيل الجمل.html",
    "/games/primary-1/unit2/توصيل الكلمات.html",
    "/games/primary-1/unit2/حارس المرمى.html",
    "/games/primary-1/unit2/سؤال وجواب.html",
    "/games/primary-1/unit2/سقوط الكلمات.html",
    "/games/primary-1/unit2/صيد الكلمات.html",
    "/games/primary-1/unit2/قطار الكلمات.html",
    "/games/primary-1/unit2/لوحة التلوين.html",
    "/games/primary-1/unit2/مدفع الكلمات.html",
    "/games/primary-1/unit3/10_الاستماع_والاختيار.html",
    "/games/primary-1/unit3/11_بناء_الجمل.html",
    "/games/primary-1/unit3/12_بناء_البرج.html",
    "/games/primary-1/unit3/13_سباق_السيارات.html",
    "/games/primary-1/unit3/14_القطار_السريع.html",
    "/games/primary-1/unit3/15_صائد_الفراشات.html",
    "/games/primary-1/unit3/16_كرة_السلة.html",
    "/games/primary-1/unit3/17_البالون_الطائر.html",
    "/games/primary-1/unit3/18_توصيل_الظل.html",
    "/games/primary-1/unit3/19_صيد_البط.html",
    "/games/primary-1/unit3/1_صيد_الكلمات.html",
    "/games/primary-1/unit3/20_السمكة_الجائعة.html",
    "/games/primary-1/unit3/2_البطاقات_التعليمية.html",
    "/games/primary-1/unit3/3_توصيل_الكلمات.html",
    "/games/primary-1/unit3/4_سؤال_وجواب.html",
    "/games/primary-1/unit3/6_فرقعة_الفقاعات.html",
    "/games/primary-1/unit3/7_الحرف_المفقود.html",
    "/games/primary-1/unit3/8_تصنيف_الكلمات.html",
    "/games/primary-1/unit3/9_ذاكرة_البطاقات.html",
    "/games/primary-1/unit3/G11_helicopter.html",
    "/games/primary-1/unit3/G12_lightning.html",
    "/games/primary-1/unit3/G13_volcano.html",
    "/games/primary-1/unit3/G14_tank.html",
    "/games/primary-1/unit3/G15_train.html",
    "/games/primary-1/unit3/G1_fishing.html",
    "/games/primary-1/unit3/G2_cannon.html",
    "/games/primary-1/unit3/G3_balloon.html",
    "/games/primary-1/unit3/G4_spaceship.html",
    "/games/primary-1/unit3/G5_archery.html",
    "/games/primary-1/unit4/10_تلوين_الكلمات.html",
    "/games/primary-1/unit4/11_مطابقة_الظل.html",
    "/games/primary-1/unit4/12_صندوق_المفاجآت.html",
    "/games/primary-1/unit4/13_قطار_الكلمات.html",
    "/games/primary-1/unit4/14_الذاكرة_الخفية.html",
    "/games/primary-1/unit4/15_بالونات_الكلمات.html",
    "/games/primary-1/unit4/16_لعبة_الغميضة.html",
    "/games/primary-1/unit4/17_طائرة_الكلمات.html",
    "/games/primary-1/unit4/18_متاهة_الحروف.html",
    "/games/primary-1/unit4/19_عجلة_الحظ.html",
    "/games/primary-1/unit4/1_طبيب_العيون.html",
    "/games/primary-1/unit4/20_صياد_الكنوز.html",
    "/games/primary-1/unit4/21_الميزان_السحري.html",
    "/games/primary-1/unit4/22_توصيل_البطاقات.html",
    "/games/primary-1/unit4/23_لغز_الكلمات.html",
    "/games/primary-1/unit4/24_سباق_السيارات.html",
    "/games/primary-1/unit4/2_حديقة_الحيوان.html",
    "/games/primary-1/unit4/3_تحدي_الحواس_الخمس.html",
    "/games/primary-1/unit4/4_روبوت_الكلمات.html",
    "/games/primary-1/unit4/5_مطبخ_الملك.html",
    "/games/primary-1/unit4/6_بناء_الجسم.html",
    "/games/primary-1/unit4/7_سباق_الصواريخ.html",
    "/games/primary-1/unit4/8_لعبة_الساحر.html",
    "/games/primary-1/unit4/9_صيد_الأسماك.html",
    "/games/primary-1/unit4/G16_lasso.html",
    "/games/primary-1/unit4/G17_wand.html",
    "/games/primary-1/unit4/G18_billiard.html",
    "/games/primary-1/unit4/G19_ufo.html",
    "/games/primary-1/unit4/G1_fishing.html",
    "/games/primary-1/unit4/G20_trapdoor.html",
    "/games/primary-1/unit4/G2_cannon.html",
    "/games/primary-1/unit4/G3_balloon.html",
    "/games/primary-1/unit4/G4_spaceship.html",
    "/games/primary-1/unit4/G5_archery.html",
    "/games/primary-1/unit5/10_قفزة_الضفدع.html",
    "/games/primary-1/unit5/11_الغواصة.html",
    "/games/primary-1/unit5/12_سفينة_الفضاء.html",
    "/games/primary-1/unit5/13_تجميع_الروبوت.html",
    "/games/primary-1/unit5/14_سباق_التزلج.html",
    "/games/primary-1/unit5/15_مزرعة_العد.html",
    "/games/primary-1/unit5/16_صندوق_الكنز.html",
    "/games/primary-1/unit5/17_الغيمة_الماطرة.html",
    "/games/primary-1/unit5/18_السلحفاة_السريعة.html",
    "/games/primary-1/unit5/19_البالونات_الطائرة.html",
    "/games/primary-1/unit5/1_صائد_الفقاعات.html",
    "/games/primary-1/unit5/20_مصنع_الحلوى.html",
    "/games/primary-1/unit5/21_إطعام_الديناصور.html",
    "/games/primary-1/unit5/22_وصفة_الساحرة.html",
    "/games/primary-1/unit5/23_الجسر_المتحرك.html",
    "/games/primary-1/unit5/24_سباق_السيارات.html",
    "/games/primary-1/unit5/25_كعكة_عيد_الميلاد.html",
    "/games/primary-1/unit5/2_القفز_فوق_المنصات.html",
    "/games/primary-1/unit5/3_السلة_السحرية.html",
    "/games/primary-1/unit5/4_قطف_الثمار.html",
    "/games/primary-1/unit5/5_ترتيب_القطار.html",
    "/games/primary-1/unit5/6_النينجا.html",
    "/games/primary-1/unit5/7_بائع_الآيس_كريم.html",
    "/games/primary-1/unit5/8_تسلق_الشجرة.html",
    "/games/primary-1/unit5/9_إطعام_الحيوانات.html",
    "/games/primary-1/unit5/G1_fishing.html",
    "/games/primary-1/unit5/G21_racecar.html",
    "/games/primary-1/unit5/G22_water.html",
    "/games/primary-1/unit5/G23_dart.html",
    "/games/primary-1/unit5/G24_slingshot.html",
    "/games/primary-1/unit5/G25_whack.html",
    "/games/primary-1/unit5/G2_cannon.html",
    "/games/primary-1/unit5/G3_balloon.html",
    "/games/primary-1/unit5/G4_spaceship.html",
    "/games/primary-1/unit5/G5_archery.html",
    "/games/primary-1/unit5/index.html",
    "/games/primary-1/unit6/10_صيد_السمك.html",
    "/games/primary-1/unit6/11_خزانة_الملابس.html",
    "/games/primary-1/unit6/12_مطعم_الحروف.html",
    "/games/primary-1/unit6/14_البولينج.html",
    "/games/primary-1/unit6/15_الرماية.html",
    "/games/primary-1/unit6/16_فقاعات_الصابون.html",
    "/games/primary-1/unit6/17_السائق_المحترف.html",
    "/games/primary-1/unit6/18_النحلة_العاملة.html",
    "/games/primary-1/unit6/19_بناء_البرج.html",
    "/games/primary-1/unit6/1_إنقاذ_الحيوانات.html",
    "/games/primary-1/unit6/20_متاهة_الجبنة.html",
    "/games/primary-1/unit6/21_القفز_بالمظلة.html",
    "/games/primary-1/unit6/23_قطار_الحروف.html",
    "/games/primary-1/unit6/24_الحصالة.html",
    "/games/primary-1/unit6/25_صانع_الشطائر.html",
    "/games/primary-1/unit6/2_حديقة_الحيوان.html",
    "/games/primary-1/unit6/3_التزلج_على_الجليد.html",
    "/games/primary-1/unit6/4_رمي_السهام.html",
    "/games/primary-1/unit6/5_كشف_المصباح.html",
    "/games/primary-1/unit6/7_مصنع_العصائر.html",
    "/games/primary-1/unit6/8_رحلة_المنطاد.html",
    "/games/primary-1/unit6/9_سباق_الخيل.html",
    "/games/primary-1/unit6/G1_fishing.html",
    "/games/primary-1/unit6/G26_balloon.html",
    "/games/primary-1/unit6/G27_boxing.html",
    "/games/primary-1/unit6/G28_paperplane.html",
    "/games/primary-1/unit6/G29_goldminer.html",
    "/games/primary-1/unit6/G2_cannon.html",
    "/games/primary-1/unit6/G30_catapult.html",
    "/games/primary-1/unit6/G3_balloon.html",
    "/games/primary-1/unit6/G4_spaceship.html",
    "/games/primary-1/unit6/G5_archery.html",
    "/games/primary-1/unit6/index.html",
    "/games/primary-2/unit1/G1_cannon.html",
    "/games/primary-2/unit1/G1_fishing.html",
    "/games/primary-2/unit1/G2_arrow.html",
    "/games/primary-2/unit1/G2_cannon.html",
    "/games/primary-2/unit1/G3_balloon.html",
    "/games/primary-2/unit1/G3_fishing.html",
    "/games/primary-2/unit1/G4_spaceship.html",
    "/games/primary-2/unit1/G5_archery.html",
    "/games/primary-2/unit1/G5_shuriken.html",
    "/games/primary-2/unit1/L1_cannon_Classroom_Greetings.html",
    "/games/primary-2/unit1/L2_arrow_Around_the_Classroom.html",
    "/games/primary-2/unit1/L3_fishing_Our_Classroom_Objects.html",
    "/games/primary-2/unit1/L4_spaceship_Lets_Write_Together.html",
    "/games/primary-2/unit2/G10_spider.html",
    "/games/primary-2/unit2/G1_fishing.html",
    "/games/primary-2/unit2/G2_cannon.html",
    "/games/primary-2/unit2/G3_balloon.html",
    "/games/primary-2/unit2/G4_spaceship.html",
    "/games/primary-2/unit2/G5_archery.html",
    "/games/primary-2/unit2/G6_bowling.html",
    "/games/primary-2/unit2/G7_soccer.html",
    "/games/primary-2/unit2/G8_basketball.html",
    "/games/primary-2/unit2/G9_boomerang.html",
    "/games/primary-2/unit2/L1_shuriken_Colors_and_Shapes.html",
    "/games/primary-2/unit2/L2_bowling_Colors_and_Shapes_Around_Us.html",
    "/games/primary-2/unit2/L3_soccer_Numbers_and_Counting.html",
    "/games/primary-2/unit2/L4_basketball_Lets_Count_Together.html",
    "/games/primary-2/unit3/G11_helicopter.html",
    "/games/primary-2/unit3/G12_lightning.html",
    "/games/primary-2/unit3/G13_volcano.html",
    "/games/primary-2/unit3/G14_tank.html",
    "/games/primary-2/unit3/G15_train.html",
    "/games/primary-2/unit3/G1_fishing.html",
    "/games/primary-2/unit3/G2_cannon.html",
    "/games/primary-2/unit3/G3_balloon.html",
    "/games/primary-2/unit3/G4_spaceship.html",
    "/games/primary-2/unit3/G5_archery.html",
    "/games/primary-2/unit3/L1_boomerang_Classroom_Actions.html",
    "/games/primary-2/unit3/L2_spider_Lets_Talk_about_Class_Routin.html",
    "/games/primary-2/unit3/L3_helicopter_All_About_Our_Classroom.html",
    "/games/primary-2/unit3/L4_lightning_Writing_About_Our_Class.html",
    "/games/primary-2/unit4/G16_lasso.html",
    "/games/primary-2/unit4/G17_wand.html",
    "/games/primary-2/unit4/G18_billiard.html",
    "/games/primary-2/unit4/G19_ufo.html",
    "/games/primary-2/unit4/G1_fishing.html",
    "/games/primary-2/unit4/G20_trapdoor.html",
    "/games/primary-2/unit4/G2_cannon.html",
    "/games/primary-2/unit4/G3_balloon.html",
    "/games/primary-2/unit4/G4_spaceship.html",
    "/games/primary-2/unit4/G5_archery.html",
    "/games/primary-2/unit4/L1_volcano_My_Family.html",
    "/games/primary-2/unit4/L2_tank_All_About_Me.html",
    "/games/primary-2/unit4/L3_train_My_Life_at_Home.html",
    "/games/primary-2/unit4/L4_lasso_Me_and_My_Family.html",
    "/games/primary-2/unit5/G1_fishing.html",
    "/games/primary-2/unit5/G21_racecar.html",
    "/games/primary-2/unit5/G22_water.html",
    "/games/primary-2/unit5/G23_dart.html",
    "/games/primary-2/unit5/G24_slingshot.html",
    "/games/primary-2/unit5/G25_whack.html",
    "/games/primary-2/unit5/G2_cannon.html",
    "/games/primary-2/unit5/G3_balloon.html",
    "/games/primary-2/unit5/G4_spaceship.html",
    "/games/primary-2/unit5/G5_archery.html",
    "/games/primary-2/unit5/L1_wand_Inside_My_Home.html",
    "/games/primary-2/unit5/L2_billiard_Whats_in_My_Home.html",
    "/games/primary-2/unit5/L3_ufo_My_Favorite_Room.html",
    "/games/primary-2/unit5/L4_trapdoor_Actions_at_Home.html",
    "/games/primary-2/unit6/G1_fishing.html",
    "/games/primary-2/unit6/G26_balloon.html",
    "/games/primary-2/unit6/G27_boxing.html",
    "/games/primary-2/unit6/G28_paperplane.html",
    "/games/primary-2/unit6/G29_goldminer.html",
    "/games/primary-2/unit6/G2_cannon.html",
    "/games/primary-2/unit6/G30_catapult.html",
    "/games/primary-2/unit6/G3_balloon.html",
    "/games/primary-2/unit6/G4_spaceship.html",
    "/games/primary-2/unit6/G5_archery.html",
    "/games/primary-2/unit6/L1_racecar_My_Home.html",
    "/games/primary-2/unit6/L2_water_Lets_Talk_About_Our_Home.html",
    "/games/primary-2/unit6/L3_dart_Where_Things_Are_in_My_Home.html",
    "/games/primary-2/unit6/L4_slingshot_I_Can_Read_and_Write_About_M.html",
    "/games/primary-3/unit1/G1_cannon.html",
    "/games/primary-3/unit1/G1_fishing.html",
    "/games/primary-3/unit1/G2_arrow.html",
    "/games/primary-3/unit1/G2_cannon.html",
    "/games/primary-3/unit1/G3_balloon.html",
    "/games/primary-3/unit1/G3_fishing.html",
    "/games/primary-3/unit1/G4_spaceship.html",
    "/games/primary-3/unit1/G5_archery.html",
    "/games/primary-3/unit1/G5_shuriken.html",
    "/games/primary-3/unit1/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit1/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit1/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit1/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit2/G10_spider.html",
    "/games/primary-3/unit2/G1_fishing.html",
    "/games/primary-3/unit2/G2_cannon.html",
    "/games/primary-3/unit2/G3_balloon.html",
    "/games/primary-3/unit2/G4_spaceship.html",
    "/games/primary-3/unit2/G5_archery.html",
    "/games/primary-3/unit2/G6_bowling.html",
    "/games/primary-3/unit2/G7_soccer.html",
    "/games/primary-3/unit2/G8_basketball.html",
    "/games/primary-3/unit2/G9_boomerang.html",
    "/games/primary-3/unit2/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit2/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit2/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit2/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit3/G11_helicopter.html",
    "/games/primary-3/unit3/G12_lightning.html",
    "/games/primary-3/unit3/G13_volcano.html",
    "/games/primary-3/unit3/G14_tank.html",
    "/games/primary-3/unit3/G15_train.html",
    "/games/primary-3/unit3/G1_fishing.html",
    "/games/primary-3/unit3/G2_cannon.html",
    "/games/primary-3/unit3/G3_balloon.html",
    "/games/primary-3/unit3/G4_spaceship.html",
    "/games/primary-3/unit3/G5_archery.html",
    "/games/primary-3/unit3/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit3/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit3/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit3/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit4/G16_lasso.html",
    "/games/primary-3/unit4/G17_wand.html",
    "/games/primary-3/unit4/G18_billiard.html",
    "/games/primary-3/unit4/G19_ufo.html",
    "/games/primary-3/unit4/G1_fishing.html",
    "/games/primary-3/unit4/G20_trapdoor.html",
    "/games/primary-3/unit4/G2_cannon.html",
    "/games/primary-3/unit4/G3_balloon.html",
    "/games/primary-3/unit4/G4_spaceship.html",
    "/games/primary-3/unit4/G5_archery.html",
    "/games/primary-3/unit4/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit4/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit4/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit4/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit5/G1_fishing.html",
    "/games/primary-3/unit5/G21_racecar.html",
    "/games/primary-3/unit5/G22_water.html",
    "/games/primary-3/unit5/G23_dart.html",
    "/games/primary-3/unit5/G24_slingshot.html",
    "/games/primary-3/unit5/G25_whack.html",
    "/games/primary-3/unit5/G2_cannon.html",
    "/games/primary-3/unit5/G3_balloon.html",
    "/games/primary-3/unit5/G4_spaceship.html",
    "/games/primary-3/unit5/G5_archery.html",
    "/games/primary-3/unit5/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit5/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit5/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit5/Lesson 4 - Word Snake.html",
    "/games/primary-3/unit6/G1_fishing.html",
    "/games/primary-3/unit6/G26_balloon.html",
    "/games/primary-3/unit6/G27_boxing.html",
    "/games/primary-3/unit6/G28_paperplane.html",
    "/games/primary-3/unit6/G29_goldminer.html",
    "/games/primary-3/unit6/G2_cannon.html",
    "/games/primary-3/unit6/G30_catapult.html",
    "/games/primary-3/unit6/G3_balloon.html",
    "/games/primary-3/unit6/G4_spaceship.html",
    "/games/primary-3/unit6/G5_archery.html",
    "/games/primary-3/unit6/Lesson 1 - Archery Quiz.html",
    "/games/primary-3/unit6/Lesson 2 - Space Blaster.html",
    "/games/primary-3/unit6/Lesson 3 - Bubble Pop.html",
    "/games/primary-3/unit6/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit1/G1_cannon.html",
    "/games/primary-4/unit1/G1_fishing.html",
    "/games/primary-4/unit1/G2_arrow.html",
    "/games/primary-4/unit1/G2_cannon.html",
    "/games/primary-4/unit1/G3_balloon.html",
    "/games/primary-4/unit1/G3_fishing.html",
    "/games/primary-4/unit1/G4_spaceship.html",
    "/games/primary-4/unit1/G5_archery.html",
    "/games/primary-4/unit1/G5_shuriken.html",
    "/games/primary-4/unit1/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit1/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit1/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit1/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit2/G10_spider.html",
    "/games/primary-4/unit2/G1_fishing.html",
    "/games/primary-4/unit2/G2_cannon.html",
    "/games/primary-4/unit2/G3_balloon.html",
    "/games/primary-4/unit2/G4_spaceship.html",
    "/games/primary-4/unit2/G5_archery.html",
    "/games/primary-4/unit2/G6_bowling.html",
    "/games/primary-4/unit2/G7_soccer.html",
    "/games/primary-4/unit2/G8_basketball.html",
    "/games/primary-4/unit2/G9_boomerang.html",
    "/games/primary-4/unit2/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit2/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit2/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit2/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit3/G11_helicopter.html",
    "/games/primary-4/unit3/G12_lightning.html",
    "/games/primary-4/unit3/G13_volcano.html",
    "/games/primary-4/unit3/G14_tank.html",
    "/games/primary-4/unit3/G15_train.html",
    "/games/primary-4/unit3/G1_fishing.html",
    "/games/primary-4/unit3/G2_cannon.html",
    "/games/primary-4/unit3/G3_balloon.html",
    "/games/primary-4/unit3/G4_spaceship.html",
    "/games/primary-4/unit3/G5_archery.html",
    "/games/primary-4/unit3/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit3/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit3/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit3/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit4/G16_lasso.html",
    "/games/primary-4/unit4/G17_wand.html",
    "/games/primary-4/unit4/G18_billiard.html",
    "/games/primary-4/unit4/G19_ufo.html",
    "/games/primary-4/unit4/G1_fishing.html",
    "/games/primary-4/unit4/G20_trapdoor.html",
    "/games/primary-4/unit4/G2_cannon.html",
    "/games/primary-4/unit4/G3_balloon.html",
    "/games/primary-4/unit4/G4_spaceship.html",
    "/games/primary-4/unit4/G5_archery.html",
    "/games/primary-4/unit4/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit4/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit4/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit4/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit5/G1_fishing.html",
    "/games/primary-4/unit5/G21_racecar.html",
    "/games/primary-4/unit5/G22_water.html",
    "/games/primary-4/unit5/G23_dart.html",
    "/games/primary-4/unit5/G24_slingshot.html",
    "/games/primary-4/unit5/G25_whack.html",
    "/games/primary-4/unit5/G2_cannon.html",
    "/games/primary-4/unit5/G3_balloon.html",
    "/games/primary-4/unit5/G4_spaceship.html",
    "/games/primary-4/unit5/G5_archery.html",
    "/games/primary-4/unit5/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit5/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit5/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit5/Lesson 4 - Word Snake.html",
    "/games/primary-4/unit6/G1_fishing.html",
    "/games/primary-4/unit6/G26_balloon.html",
    "/games/primary-4/unit6/G27_boxing.html",
    "/games/primary-4/unit6/G28_paperplane.html",
    "/games/primary-4/unit6/G29_goldminer.html",
    "/games/primary-4/unit6/G2_cannon.html",
    "/games/primary-4/unit6/G30_catapult.html",
    "/games/primary-4/unit6/G3_balloon.html",
    "/games/primary-4/unit6/G4_spaceship.html",
    "/games/primary-4/unit6/G5_archery.html",
    "/games/primary-4/unit6/Lesson 1 - Archery Quiz.html",
    "/games/primary-4/unit6/Lesson 2 - Space Blaster.html",
    "/games/primary-4/unit6/Lesson 3 - Bubble Pop.html",
    "/games/primary-4/unit6/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit1/G1_cannon.html",
    "/games/primary-5/unit1/G1_fishing.html",
    "/games/primary-5/unit1/G2_arrow.html",
    "/games/primary-5/unit1/G2_cannon.html",
    "/games/primary-5/unit1/G3_balloon.html",
    "/games/primary-5/unit1/G3_fishing.html",
    "/games/primary-5/unit1/G4_spaceship.html",
    "/games/primary-5/unit1/G5_archery.html",
    "/games/primary-5/unit1/G5_shuriken.html",
    "/games/primary-5/unit1/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit1/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit1/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit1/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit2/G10_spider.html",
    "/games/primary-5/unit2/G1_fishing.html",
    "/games/primary-5/unit2/G2_cannon.html",
    "/games/primary-5/unit2/G3_balloon.html",
    "/games/primary-5/unit2/G4_spaceship.html",
    "/games/primary-5/unit2/G5_archery.html",
    "/games/primary-5/unit2/G6_bowling.html",
    "/games/primary-5/unit2/G7_soccer.html",
    "/games/primary-5/unit2/G8_basketball.html",
    "/games/primary-5/unit2/G9_boomerang.html",
    "/games/primary-5/unit2/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit2/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit2/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit2/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit3/G11_helicopter.html",
    "/games/primary-5/unit3/G12_lightning.html",
    "/games/primary-5/unit3/G13_volcano.html",
    "/games/primary-5/unit3/G14_tank.html",
    "/games/primary-5/unit3/G15_train.html",
    "/games/primary-5/unit3/G1_fishing.html",
    "/games/primary-5/unit3/G2_cannon.html",
    "/games/primary-5/unit3/G3_balloon.html",
    "/games/primary-5/unit3/G4_spaceship.html",
    "/games/primary-5/unit3/G5_archery.html",
    "/games/primary-5/unit3/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit3/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit3/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit3/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit4/G16_lasso.html",
    "/games/primary-5/unit4/G17_wand.html",
    "/games/primary-5/unit4/G18_billiard.html",
    "/games/primary-5/unit4/G19_ufo.html",
    "/games/primary-5/unit4/G1_fishing.html",
    "/games/primary-5/unit4/G20_trapdoor.html",
    "/games/primary-5/unit4/G2_cannon.html",
    "/games/primary-5/unit4/G3_balloon.html",
    "/games/primary-5/unit4/G4_spaceship.html",
    "/games/primary-5/unit4/G5_archery.html",
    "/games/primary-5/unit4/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit4/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit4/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit4/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit5/G1_fishing.html",
    "/games/primary-5/unit5/G21_racecar.html",
    "/games/primary-5/unit5/G22_water.html",
    "/games/primary-5/unit5/G23_dart.html",
    "/games/primary-5/unit5/G24_slingshot.html",
    "/games/primary-5/unit5/G25_whack.html",
    "/games/primary-5/unit5/G2_cannon.html",
    "/games/primary-5/unit5/G3_balloon.html",
    "/games/primary-5/unit5/G4_spaceship.html",
    "/games/primary-5/unit5/G5_archery.html",
    "/games/primary-5/unit5/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit5/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit5/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit5/Lesson 4 - Word Snake.html",
    "/games/primary-5/unit6/G1_fishing.html",
    "/games/primary-5/unit6/G26_balloon.html",
    "/games/primary-5/unit6/G27_boxing.html",
    "/games/primary-5/unit6/G28_paperplane.html",
    "/games/primary-5/unit6/G29_goldminer.html",
    "/games/primary-5/unit6/G2_cannon.html",
    "/games/primary-5/unit6/G30_catapult.html",
    "/games/primary-5/unit6/G3_balloon.html",
    "/games/primary-5/unit6/G4_spaceship.html",
    "/games/primary-5/unit6/G5_archery.html",
    "/games/primary-5/unit6/Lesson 1 - Archery Quiz.html",
    "/games/primary-5/unit6/Lesson 2 - Space Blaster.html",
    "/games/primary-5/unit6/Lesson 3 - Bubble Pop.html",
    "/games/primary-5/unit6/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit1/G1_cannon.html",
    "/games/primary-6/unit1/G1_fishing.html",
    "/games/primary-6/unit1/G2_arrow.html",
    "/games/primary-6/unit1/G2_cannon.html",
    "/games/primary-6/unit1/G3_balloon.html",
    "/games/primary-6/unit1/G3_fishing.html",
    "/games/primary-6/unit1/G4_spaceship.html",
    "/games/primary-6/unit1/G5_archery.html",
    "/games/primary-6/unit1/G5_shuriken.html",
    "/games/primary-6/unit1/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit1/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit1/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit1/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit2/G10_spider.html",
    "/games/primary-6/unit2/G1_fishing.html",
    "/games/primary-6/unit2/G2_cannon.html",
    "/games/primary-6/unit2/G3_balloon.html",
    "/games/primary-6/unit2/G4_spaceship.html",
    "/games/primary-6/unit2/G5_archery.html",
    "/games/primary-6/unit2/G6_bowling.html",
    "/games/primary-6/unit2/G7_soccer.html",
    "/games/primary-6/unit2/G8_basketball.html",
    "/games/primary-6/unit2/G9_boomerang.html",
    "/games/primary-6/unit2/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit2/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit2/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit2/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit3/G11_helicopter.html",
    "/games/primary-6/unit3/G12_lightning.html",
    "/games/primary-6/unit3/G13_volcano.html",
    "/games/primary-6/unit3/G14_tank.html",
    "/games/primary-6/unit3/G15_train.html",
    "/games/primary-6/unit3/G1_fishing.html",
    "/games/primary-6/unit3/G2_cannon.html",
    "/games/primary-6/unit3/G3_balloon.html",
    "/games/primary-6/unit3/G4_spaceship.html",
    "/games/primary-6/unit3/G5_archery.html",
    "/games/primary-6/unit3/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit3/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit3/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit3/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit4/G16_lasso.html",
    "/games/primary-6/unit4/G17_wand.html",
    "/games/primary-6/unit4/G18_billiard.html",
    "/games/primary-6/unit4/G19_ufo.html",
    "/games/primary-6/unit4/G1_fishing.html",
    "/games/primary-6/unit4/G20_trapdoor.html",
    "/games/primary-6/unit4/G2_cannon.html",
    "/games/primary-6/unit4/G3_balloon.html",
    "/games/primary-6/unit4/G4_spaceship.html",
    "/games/primary-6/unit4/G5_archery.html",
    "/games/primary-6/unit4/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit4/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit4/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit4/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit5/G1_fishing.html",
    "/games/primary-6/unit5/G21_racecar.html",
    "/games/primary-6/unit5/G22_water.html",
    "/games/primary-6/unit5/G23_dart.html",
    "/games/primary-6/unit5/G24_slingshot.html",
    "/games/primary-6/unit5/G25_whack.html",
    "/games/primary-6/unit5/G2_cannon.html",
    "/games/primary-6/unit5/G3_balloon.html",
    "/games/primary-6/unit5/G4_spaceship.html",
    "/games/primary-6/unit5/G5_archery.html",
    "/games/primary-6/unit5/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit5/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit5/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit5/Lesson 4 - Word Snake.html",
    "/games/primary-6/unit6/G1_fishing.html",
    "/games/primary-6/unit6/G26_balloon.html",
    "/games/primary-6/unit6/G27_boxing.html",
    "/games/primary-6/unit6/G28_paperplane.html",
    "/games/primary-6/unit6/G29_goldminer.html",
    "/games/primary-6/unit6/G2_cannon.html",
    "/games/primary-6/unit6/G30_catapult.html",
    "/games/primary-6/unit6/G3_balloon.html",
    "/games/primary-6/unit6/G4_spaceship.html",
    "/games/primary-6/unit6/G5_archery.html",
    "/games/primary-6/unit6/Lesson 1 - Archery Quiz.html",
    "/games/primary-6/unit6/Lesson 2 - Space Blaster.html",
    "/games/primary-6/unit6/Lesson 3 - Bubble Pop.html",
    "/games/primary-6/unit6/Lesson 4 - Word Snake.html",
    "/grammar_banks/Prep1_English_Unit1_150_MCQs.json",
    "/grammar_banks/Prep1_English_Unit2_150_MCQs.json",
    "/grammar_banks/Prep1_English_Unit3_150_MCQs.json",
    "/grammar_banks/Prep1_English_Unit4_150_MCQs.json",
    "/grammar_banks/Prep1_English_Unit5_150_MCQs.json",
    "/grammar_banks/Prep1_English_Unit6_150_MCQs.json",
    "/grammar_banks/Prep2_English_Unit1_150_MCQs.json",
    "/grammar_banks/Prep2_English_Unit2_150_MCQs.json",
    "/grammar_banks/Prep2_English_Unit3_150_MCQs.json",
    "/grammar_banks/Prep2_English_Unit4_150_MCQs.json",
    "/grammar_banks/Prep2_English_Unit5_150_MCQs.json",
    "/grammar_banks/Prep2_English_Unit6_150_MCQs.json",
    "/grammar_banks/Primary 2 English - 180 Questions Quiz.json",
    "/grammar_banks/Primary3_English_Unit1_180_MCQs.json",
    "/grammar_banks/Primary3_English_Unit2_180_MCQs.json",
    "/grammar_banks/Primary3_English_Unit3_180_MCQs.json",
    "/grammar_banks/Primary3_English_Unit4_180_MCQs.json",
    "/grammar_banks/Primary3_English_Unit5_180_MCQs.json",
    "/grammar_banks/Primary3_English_Unit6_180_MCQs.json",
    "/grammar_banks/Primary4_English_Unit1_180_MCQs.json",
    "/grammar_banks/Primary4_English_Unit2_180_MCQs.json",
    "/grammar_banks/Primary4_English_Unit3_180_MCQs.json",
    "/grammar_banks/Primary4_English_Unit4_180_MCQs.json",
    "/grammar_banks/Primary4_English_Unit5_180_MCQs.json",
    "/grammar_banks/Primary4_English_Unit6_180_MCQs.json",
    "/grammar_banks/Primary5_English_Unit1_180_MCQs.json",
    "/grammar_banks/Primary5_English_Unit2_180_MCQs.json",
    "/grammar_banks/Primary5_English_Unit3_180_MCQs.json",
    "/grammar_banks/Primary5_English_Unit4_180_MCQs.json",
    "/grammar_banks/Primary5_English_Unit5_180_MCQs.json",
    "/grammar_banks/Primary5_English_Unit6_180_MCQs.json",
    "/grammar_banks/Primary6_English_600_MCQs.json",
    "/images/book_p1.jpg",
    "/images/book_pmid.jpg",
    "/images/book_prep.jpg",
    "/images/clean_bg.png",
    "/images/cover_2027.jpg",
    "/images/dashboard_bg.png",
    "/images/feat_book.jpg",
    "/images/feat_student.jpg",
    "/images/feat_teacher.jpg",
    "/images/game_icon_1.png",
    "/images/game_icon_2.png",
    "/images/game_icon_3.png",
    "/images/game_icon_4.png",
    "/images/login_bg.png",
    "/images/logo_icon.png",
    "/images/pixar_bg.png",
    "/images/prep_1.png",
    "/images/prep_2.png",
    "/images/prep_3.png",
    "/images/prep_card.jpg",
    "/images/primary_1.png",
    "/images/primary_2.png",
    "/images/primary_3.png",
    "/images/primary_4.png",
    "/images/primary_5.png",
    "/images/primary_6.png",
    "/images/primary_card.jpg",
    "/images/unit_1.png",
    "/images/unit_2.png",
    "/images/unit_3.png",
    "/images/unit_4.png",
    "/images/unit_5.png",
    "/images/unit_6.png",
    "/images/books/p1/1.jpg",
    "/images/books/p1/10.jpg",
    "/images/books/p1/11.jpg",
    "/images/books/p1/12.jpg",
    "/images/books/p1/13.jpg",
    "/images/books/p1/14.jpg",
    "/images/books/p1/15.jpg",
    "/images/books/p1/16.jpg",
    "/images/books/p1/17.jpg",
    "/images/books/p1/18.jpg",
    "/images/books/p1/19.jpg",
    "/images/books/p1/2.jpg",
    "/images/books/p1/20.jpg",
    "/images/books/p1/21.jpg",
    "/images/books/p1/22.jpg",
    "/images/books/p1/23.jpg",
    "/images/books/p1/24.jpg",
    "/images/books/p1/25.jpg",
    "/images/books/p1/26.jpg",
    "/images/books/p1/27.jpg",
    "/images/books/p1/28.jpg",
    "/images/books/p1/29.jpg",
    "/images/books/p1/3.jpg",
    "/images/books/p1/30.jpg",
    "/images/books/p1/31.jpg",
    "/images/books/p1/32.jpg",
    "/images/books/p1/33.jpg",
    "/images/books/p1/34.jpg",
    "/images/books/p1/35.jpg",
    "/images/books/p1/36.jpg",
    "/images/books/p1/37.jpg",
    "/images/books/p1/38.jpg",
    "/images/books/p1/39.jpg",
    "/images/books/p1/4.jpg",
    "/images/books/p1/40.jpg",
    "/images/books/p1/41.jpg",
    "/images/books/p1/42.jpg",
    "/images/books/p1/43.jpg",
    "/images/books/p1/44.jpg",
    "/images/books/p1/45.jpg",
    "/images/books/p1/46.jpg",
    "/images/books/p1/47.jpg",
    "/images/books/p1/48.jpg",
    "/images/books/p1/49.jpg",
    "/images/books/p1/5.jpg",
    "/images/books/p1/50.jpg",
    "/images/books/p1/51.jpg",
    "/images/books/p1/52.jpg",
    "/images/books/p1/53.jpg",
    "/images/books/p1/54.jpg",
    "/images/books/p1/55.jpg",
    "/images/books/p1/56.jpg",
    "/images/books/p1/57.jpg",
    "/images/books/p1/58.jpg",
    "/images/books/p1/59.jpg",
    "/images/books/p1/6.jpg",
    "/images/books/p1/60.jpg",
    "/images/books/p1/61.jpg",
    "/images/books/p1/62.jpg",
    "/images/books/p1/63.jpg",
    "/images/books/p1/64.jpg",
    "/images/books/p1/65.jpg",
    "/images/books/p1/66.jpg",
    "/images/books/p1/67.jpg",
    "/images/books/p1/68.jpg",
    "/images/books/p1/69.jpg",
    "/images/books/p1/7.jpg",
    "/images/books/p1/70.jpg",
    "/images/books/p1/71.jpg",
    "/images/books/p1/72.jpg",
    "/images/books/p1/8.jpg",
    "/images/books/p1/9.jpg",
    "/images/books/p1/page_1.png",
    "/images/books/p1/page_10.png",
    "/images/books/p1/page_11.png",
    "/images/books/p1/page_12.png",
    "/images/books/p1/page_13.png",
    "/images/books/p1/page_14.png",
    "/images/books/p1/page_15.png",
    "/images/books/p1/page_16.png",
    "/images/books/p1/page_17.png",
    "/images/books/p1/page_18.png",
    "/images/books/p1/page_19.png",
    "/images/books/p1/page_2.png",
    "/images/books/p1/page_20.png",
    "/images/books/p1/page_3.png",
    "/images/books/p1/page_4.png",
    "/images/books/p1/page_5.png",
    "/images/books/p1/page_6.png",
    "/images/books/p1/page_7.png",
    "/images/books/p1/page_8.png",
    "/images/books/p1/page_9.png",
    "/images/books/p1/items/p10_board.jpg",
    "/images/books/p1/items/p10_ill.jpg",
    "/images/books/p1/items/p10_insect.jpg",
    "/images/books/p1/items/p10_insect2.jpg",
    "/images/books/p1/items/p10_standup.jpg",
    "/images/books/p1/items/p3_friends.jpg",
    "/images/books/p1/items/p3_hello.jpg",
    "/images/books/p1/items/p3_play.jpg",
    "/images/books/p1/items/p4_hw_table.jpg",
    "/images/books/p1/items/p4_hw_teacher.jpg",
    "/images/books/p1/items/p4_hw_tiger.jpg",
    "/images/books/p1/items/p4_hw_tomato.jpg",
    "/images/books/p1/items/p4_hw_tree.jpg",
    "/images/books/p1/items/p4_table.jpg",
    "/images/books/p1/items/p4_teacher.jpg",
    "/images/books/p1/items/p4_tiger.jpg",
    "/images/books/p1/items/p4_tomato.jpg",
    "/images/books/p1/items/p4_tree.jpg",
    "/images/books/p1/items/p7_bag.jpg",
    "/images/books/p1/items/p7_board.jpg",
    "/images/books/p1/items/p7_book.jpg",
    "/images/books/p1/items/p7_hw_bag.jpg",
    "/images/books/p1/items/p7_hw_board.jpg",
    "/images/books/p1/items/p7_hw_book.jpg",
    "/images/books/p1/items/p7_hw_chair.jpg",
    "/images/books/p1/items/p7_hw_desk.jpg",
    "/images/books/p1/items/p7_hw_pencil.jpg",
    "/images/books/p1/items/p7_pencil.jpg",
    "/images/books/p1/items/p8_hw_ill.jpg",
    "/images/books/p1/items/p8_hw_in.jpg",
    "/images/books/p1/items/p8_hw_ink.jpg",
    "/images/books/p1/items/p8_hw_insect.jpg",
    "/images/books/p1/items/p8_ill.jpg",
    "/images/books/p1/items/p8_in.jpg",
    "/images/books/p1/items/p8_ink.jpg",
    "/images/books/p1/items/p8_insect.jpg",
    "/images/books/p1/items/p9_bag.jpg",
    "/images/books/p1/items/p9_book.jpg",
    "/images/books/p1/items/p9_chair.jpg",
    "/images/books/p1/items/p9_desk.jpg",
    "/images/books/p1/items/p9_ill.jpg",
    "/images/books/p1/items/p9_in.jpg",
    "/images/books/p1/items/p9_ink.jpg",
    "/images/books/p1/items/p9_insect.jpg",
    "/images/books/p1/items/p9_pencil.jpg",
    "/images/books/p1/items/p9_sitdown.jpg",
    "/images/books/p2/page_1.png",
    "/images/books/p2/page_10.png",
    "/images/books/p2/page_2.png",
    "/images/books/p2/page_3.png",
    "/images/books/p2/page_4.png",
    "/images/books/p2/page_5.png",
    "/images/books/p2/page_6.png",
    "/images/books/p2/page_7.png",
    "/images/books/p2/page_8.png",
    "/images/books/p2/page_9.png",
    "/images/books/p3/page_1.png",
    "/images/books/p3/page_10.png",
    "/images/books/p3/page_2.png",
    "/images/books/p3/page_3.png",
    "/images/books/p3/page_4.png",
    "/images/books/p3/page_5.png",
    "/images/books/p3/page_6.png",
    "/images/books/p3/page_7.png",
    "/images/books/p3/page_8.png",
    "/images/books/p3/page_9.png",
    "/js/auth.js",
    "/js/banner.js",
    "/js/data.js",
    "/js/game-enhancements.js",
    "/js/p1_book_data.js",
    "/js/p1_interactive_app.js",
    "/js/p2_pagesData.js",
    "/js/pagesData.js",
    "/scratch/build_full_p1_db.js",
    "/scratch/gen_full_db.ps1",
    "/scratch/update_p11_to_p30.js",
    "/__pycache__/solve_master_prep3.cpython-312.pyc"
];

const corePages = [
  '/',
  '/index.html',
  '/dashboard.html',
  '/grade.html',
  '/admin.html',
  '/unit.html',
  '/exams.html',
  '/pdf-files.html'
];
urlsToCache.push(...corePages);

self.addEventListener('install', event => {
    self.skipWaiting();
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(cache => {
                return Promise.all(
                    urlsToCache.map(url => {
                        return cache.add(url).catch(err => {
                            console.warn('Failed to cache:', url, err);
                        });
                    })
                );
            })
    );
});

self.addEventListener('activate', event => {
    event.waitUntil(
        caches.keys().then(cacheNames => {
            return Promise.all(
                cacheNames.map(cacheName => {
                    if (cacheName !== CACHE_NAME) {
                        console.log('Deleting old cache:', cacheName);
                        return caches.delete(cacheName);
                    }
                })
            );
        }).then(() => self.clients.claim())
    );
});

// Network-First with Cache Fallback strategy
self.addEventListener('fetch', event => {
    if (event.request.method !== 'GET') return;

    event.respondWith(
        fetch(event.request)
            .then(networkResponse => {
                if (networkResponse && networkResponse.status === 200 && networkResponse.type === 'basic') {
                    const responseToCache = networkResponse.clone();
                    caches.open(CACHE_NAME).then(cache => {
                        cache.put(event.request, responseToCache).catch(() => {});
                    });
                }
                return networkResponse;
            })
            .catch(() => {
                return caches.match(event.request);
            })
    );
});
