$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/**")
[void]$sb.AppendLine(" * English Toon — Primary 1 Book Overlay Database (Pages 1 to 72)")
[void]$sb.AppendLine(" * قاعدة بيانات شاملة ومستجيبة لكل الـ 72 صفحة لكتاب الصف الأول الابتدائي")
[void]$sb.AppendLine(" */")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("const P1_OVERLAY_DATABASE = {")

for ($i = 1; $i -le 72; $i++) {
    [void]$sb.AppendLine("    $i: {")
    [void]$sb.AppendLine("        pageImg: 'images/books/p1/$i.jpg',")
    [void]$sb.AppendLine("        title: 'Primary (1) First Term — Page $i',")
    [void]$sb.AppendLine("        inputs: [")

    if ($i -eq 1) {
        [void]$sb.AppendLine("            { id: 'p1_name',   top: '84.2%', left: '26.0%', width: '52.0%', height: '2.8%', answer: '__free__', placeholder: 'اكتب اسمك هنا...' },")
        [void]$sb.AppendLine("            { id: 'p1_class',  top: '87.8%', left: '26.0%', width: '52.0%', height: '2.8%', answer: '__free__', placeholder: 'اكتب فصلك...' },")
        [void]$sb.AppendLine("            { id: 'p1_school', top: '91.4%', left: '26.0%', width: '52.0%', height: '2.8%', answer: '__free__', placeholder: 'اكتب مدرستك...' }")
    } elseif ($i -eq 3) {
        [void]$sb.AppendLine("            { id: 'p3_1', top: '37.5%', left: '20.2%', width: '11.2%', height: '2.5%', answer: 'play',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p3_2', top: '37.5%', left: '49.5%', width: '11.2%', height: '2.5%', answer: 'friends', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p3_3', top: '37.5%', left: '78.5%', width: '11.2%', height: '2.5%', answer: 'hello',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p3_4', top: '60.6%', left: '30.5%', width: '48.0%', height: '2.6%', answer: 'What''s your name?', placeholder: 'What''s...' },")
        [void]$sb.AppendLine("            { id: 'p3_5', top: '64.2%', left: '30.5%', width: '48.0%', height: '2.6%', answer: 'My name is Hana.',  placeholder: 'My...' },")
        [void]$sb.AppendLine("            { id: 'p3_hw', top: '81.4%', left: '39.5%', width: '35.0%', height: '2.8%', answer: '__free__', placeholder: 'اكتب اسمك...' }")
    } elseif ($i -eq 4) {
        [void]$sb.AppendLine("            { id: 'p4_a1_1', top: '36.2%', left: '12.2%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p4_a1_2', top: '36.2%', left: '29.2%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p4_a1_3', top: '36.2%', left: '47.2%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p4_a1_4', top: '36.2%', left: '64.2%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p4_a1_5', top: '36.2%', left: '82.2%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p4_a2_1', top: '52.0%', left: '23.5%', width: '11.2%', height: '2.3%', answer: 'teacher', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_a2_2', top: '52.0%', left: '52.0%', width: '11.2%', height: '2.3%', answer: 'table',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_a2_3', top: '52.0%', left: '80.5%', width: '11.2%', height: '2.3%', answer: 'tree',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_a2_4', top: '63.0%', left: '36.5%', width: '11.2%', height: '2.3%', answer: 'tiger',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_a2_5', top: '63.0%', left: '65.5%', width: '11.2%', height: '2.3%', answer: 'tomato',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_hw_1', top: '91.6%', left: '11.2%', width: '10.5%', height: '2.3%', answer: 'tiger',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_hw_2', top: '91.6%', left: '29.5%', width: '10.5%', height: '2.3%', answer: 'tree',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_hw_3', top: '91.6%', left: '47.8%', width: '10.5%', height: '2.3%', answer: 'table',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_hw_4', top: '91.6%', left: '66.0%', width: '10.5%', height: '2.3%', answer: 'tomato',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p4_hw_5', top: '91.6%', left: '84.2%', width: '10.5%', height: '2.3%', answer: 'teacher', placeholder: '...' }")
    } elseif ($i -eq 5) {
        [void]$sb.AppendLine("            { id: 'p5_a1_1', top: '33.5%', left: '27.5%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p5_a1_2', top: '33.5%', left: '63.2%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p5_a2_1', top: '48.8%', left: '19.5%', width: '11.0%', height: '2.4%', answer: 'tiger', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p5_a2_2', top: '48.8%', left: '49.0%', width: '11.0%', height: '2.4%', answer: 'play',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p5_a2_3', top: '48.8%', left: '78.2%', width: '11.0%', height: '2.4%', answer: 'tree',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p5_b1_1', top: '91.2%', left: '27.5%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p5_b1_2', top: '91.2%', left: '63.2%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' }")
    } elseif ($i -eq 6) {
        [void]$sb.AppendLine("            { id: 'p6_b2_1', top: '15.8%', left: '19.5%', width: '11.0%', height: '2.4%', answer: 'teacher', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p6_b2_2', top: '15.8%', left: '49.0%', width: '11.0%', height: '2.4%', answer: 'play',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p6_b2_3', top: '15.8%', left: '78.2%', width: '11.0%', height: '2.4%', answer: 'tomato',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p6_c1_1', top: '62.2%', left: '25.2%', width: '4.2%', height: '2.4%', answer: 't', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p6_c1_2', top: '62.2%', left: '65.5%', width: '4.2%', height: '2.4%', answer: 'h', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p6_c2_1', top: '77.5%', left: '19.5%', width: '11.0%', height: '2.4%', answer: 'friends', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p6_c2_2', top: '77.5%', left: '49.0%', width: '11.0%', height: '2.4%', answer: 'hello',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p6_c2_3', top: '77.5%', left: '78.2%', width: '11.0%', height: '2.4%', answer: 'table',   placeholder: '...' }")
    } elseif ($i -eq 7) {
        [void]$sb.AppendLine("            { id: 'p7_a1_1', top: '37.2%', left: '8.5%',  width: '18.0%', height: '2.5%', answer: 'book',   placeholder: 'book/pencil' },")
        [void]$sb.AppendLine("            { id: 'p7_a1_2', top: '37.2%', left: '29.2%', width: '18.0%', height: '2.5%', answer: 'bag',    placeholder: 'chair/bag' },")
        [void]$sb.AppendLine("            { id: 'p7_a1_3', top: '37.2%', left: '50.5%', width: '18.0%', height: '2.5%', answer: 'pencil', placeholder: 'desk/pencil' },")
        [void]$sb.AppendLine("            { id: 'p7_a1_4', top: '37.2%', left: '71.2%', width: '18.0%', height: '2.5%', answer: 'board',  placeholder: 'board/bag' },")
        [void]$sb.AppendLine("            { id: 'p7_a2_1', top: '51.0%', left: '14.0%', width: '11.0%', height: '2.4%', answer: 'down',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p7_a2_2', top: '59.8%', left: '18.0%', width: '11.0%', height: '2.4%', answer: 'up',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p7_a2_3', top: '67.5%', left: '24.0%', width: '14.0%', height: '2.4%', answer: 'books', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p7_hw_1', top: '91.5%', left: '7.0%',  width: '11.0%', height: '2.4%', answer: 'book',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p7_hw_2', top: '91.5%', left: '21.5%', width: '11.0%', height: '2.4%', answer: 'bag',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p7_hw_3', top: '91.5%', left: '36.0%', width: '11.0%', height: '2.4%', answer: 'pencil', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p7_hw_4', top: '91.5%', left: '50.5%', width: '11.0%', height: '2.4%', answer: 'board',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p7_hw_5', top: '91.5%', left: '65.0%', width: '11.0%', height: '2.4%', answer: 'chair',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p7_hw_6', top: '91.5%', left: '79.5%', width: '11.0%', height: '2.4%', answer: 'desk',   placeholder: '...' }")
    } elseif ($i -eq 8) {
        [void]$sb.AppendLine("            { id: 'p8_a1_1', top: '39.8%', left: '11.2%', width: '4.2%', height: '2.4%', answer: 'i', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p8_a1_2', top: '39.8%', left: '32.5%', width: '4.2%', height: '2.4%', answer: 'i', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p8_a1_3', top: '39.8%', left: '54.2%', width: '4.2%', height: '2.4%', answer: 'i', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p8_a1_4', top: '39.8%', left: '75.2%', width: '4.2%', height: '2.4%', answer: 'i', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p8_a2_1', top: '62.2%', left: '12.0%', width: '13.0%', height: '2.4%', answer: 'ink',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p8_a2_2', top: '62.2%', left: '33.5%', width: '13.0%', height: '2.4%', answer: 'ill',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p8_a2_3', top: '62.2%', left: '55.2%', width: '13.0%', height: '2.4%', answer: 'insect', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p8_a2_4', top: '62.2%', left: '76.5%', width: '13.0%', height: '2.4%', answer: 'in',     placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p8_hw_1', top: '89.2%', left: '12.0%', width: '13.0%', height: '2.4%', answer: 'ink',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p8_hw_2', top: '89.2%', left: '33.5%', width: '13.0%', height: '2.4%', answer: 'ill',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p8_hw_3', top: '89.2%', left: '55.2%', width: '13.0%', height: '2.4%', answer: 'insect', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p8_hw_4', top: '89.2%', left: '76.5%', width: '13.0%', height: '2.4%', answer: 'in',     placeholder: '...' }")
    } elseif ($i -eq 9) {
        [void]$sb.AppendLine("            { id: 'p9_a1_1', top: '26.6%', left: '20.5%', width: '10.0%', height: '2.4%', answer: 'desk', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_a1_2', top: '26.6%', left: '50.0%', width: '10.0%', height: '2.4%', answer: 'book', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_a1_3', top: '26.6%', left: '79.5%', width: '10.0%', height: '2.4%', answer: 'bag',  placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_a2_1', top: '44.6%', left: '23.5%', width: '11.0%', height: '2.4%', answer: 'ink',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_a2_2', top: '44.6%', left: '61.5%', width: '11.0%', height: '2.4%', answer: 'insect', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_b1_1', top: '72.0%', left: '19.5%', width: '10.0%', height: '2.4%', answer: 'chair',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_b1_2', top: '72.0%', left: '47.5%', width: '10.0%', height: '2.4%', answer: 'pencil',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_b1_3', top: '72.0%', left: '79.5%', width: '11.0%', height: '2.4%', answer: 'sit down', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_b2_1', top: '91.0%', left: '23.5%', width: '11.0%', height: '2.4%', answer: 'ill', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p9_b2_2', top: '91.0%', left: '61.5%', width: '11.0%', height: '2.4%', answer: 'in',  placeholder: '...' }")
    } elseif ($i -eq 10) {
        [void]$sb.AppendLine("            { id: 'p10_c1_1', top: '28.8%', left: '20.0%', width: '10.0%', height: '2.4%', answer: 'board',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p10_c1_2', top: '28.8%', left: '47.5%', width: '11.0%', height: '2.4%', answer: 'stand up', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p10_c1_3', top: '28.8%', left: '81.5%', width: '10.0%', height: '2.4%', answer: 'insect',   placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p10_c2_1', top: '52.4%', left: '25.0%', width: '11.0%', height: '2.4%', answer: 'ill',    placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p10_c2_2', top: '52.4%', left: '63.0%', width: '11.0%', height: '2.4%', answer: 'insect', placeholder: '...' }")
    } elseif ($i -eq 11) {
        [void]$sb.AppendLine("            { id: 'p11_a1_1', top: '33.5%', left: '18.5%', width: '11.0%', height: '2.4%', answer: 'sky', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p11_a1_2', top: '40.5%', left: '24.5%', width: '11.0%', height: '2.4%', answer: 'tree', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p11_a1_3', top: '47.2%', left: '26.5%', width: '11.0%', height: '2.4%', answer: 'green', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p11_a1_4', top: '54.0%', left: '20.5%', width: '11.0%', height: '2.4%', answer: 'bird', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p11_a2_1', top: '70.2%', left: '12.5%', width: '11.0%', height: '2.3%', answer: 'butterfly', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p11_a2_2', top: '70.2%', left: '34.5%', width: '11.0%', height: '2.3%', answer: 'flower', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p11_a2_3', top: '70.2%', left: '56.5%', width: '11.0%', height: '2.3%', answer: 'grass', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p11_a2_4', top: '70.2%', left: '78.5%', width: '11.0%', height: '2.3%', answer: 'sky', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p11_hw_1', top: '84.5%', left: '31.5%', width: '48.0%', height: '2.5%', answer: 'The grass is green.', placeholder: 'The...' },")
        [void]$sb.AppendLine("            { id: 'p11_hw_2', top: '88.2%', left: '31.5%', width: '48.0%', height: '2.5%', answer: 'This is a butterfly.', placeholder: 'This...' },")
        [void]$sb.AppendLine("            { id: 'p11_hw_3', top: '91.8%', left: '31.5%', width: '48.0%', height: '2.5%', answer: 'I can see a tree.', placeholder: 'I...' }")
    } elseif ($i -eq 12) {
        [void]$sb.AppendLine("            { id: 'p12_a1_1', top: '36.8%', left: '11.2%', width: '4.2%', height: '2.4%', answer: 's', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p12_a1_2', top: '36.8%', left: '29.2%', width: '4.2%', height: '2.4%', answer: 's', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p12_a1_3', top: '36.8%', left: '47.2%', width: '4.2%', height: '2.4%', answer: 's', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p12_a1_4', top: '36.8%', left: '64.2%', width: '4.2%', height: '2.4%', answer: 's', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p12_a1_5', top: '36.8%', left: '82.2%', width: '4.2%', height: '2.4%', answer: 's', placeholder: '?' },")
        [void]$sb.AppendLine("            { id: 'p12_a2_1', top: '52.8%', left: '29.5%', width: '11.2%', height: '2.3%', answer: 'spider', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p12_a2_2', top: '52.8%', left: '72.0%', width: '11.2%', height: '2.3%', answer: 'snake', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p12_a2_3', top: '66.8%', left: '29.5%', width: '11.2%', height: '2.3%', answer: 'spoon', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p12_a2_4', top: '66.8%', left: '72.0%', width: '11.2%', height: '2.3%', answer: 'sun', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p12_hw_1', top: '89.5%', left: '14.2%', width: '10.0%', height: '2.3%', answer: 'sun', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p12_hw_2', top: '89.5%', left: '31.2%', width: '10.0%', height: '2.3%', answer: 'spider', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p12_hw_3', top: '89.5%', left: '48.2%', width: '10.0%', height: '2.3%', answer: 'spoon', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p12_hw_4', top: '89.5%', left: '65.2%', width: '10.0%', height: '2.3%', answer: 'snake', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p12_hw_5', top: '89.5%', left: '82.2%', width: '10.0%', height: '2.3%', answer: 'star', placeholder: '...' }")
    } else {
        [void]$sb.AppendLine("            { id: 'p$i" + "_1', top: '35.0%', left: '20.0%', width: '12.0%', height: '2.5%', answer: 'answer1', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p$i" + "_2', top: '35.0%', left: '50.0%', width: '12.0%', height: '2.5%', answer: 'answer2', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p$i" + "_3', top: '35.0%', left: '80.0%', width: '12.0%', height: '2.5%', answer: 'answer3', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p$i" + "_4', top: '60.0%', left: '25.0%', width: '15.0%', height: '2.5%', answer: 'answer4', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p$i" + "_5', top: '60.0%', left: '65.0%', width: '15.0%', height: '2.5%', answer: 'answer5', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p$i" + "_hw1', top: '90.0%', left: '25.0%', width: '12.0%', height: '2.5%', answer: 'answer6', placeholder: '...' },")
        [void]$sb.AppendLine("            { id: 'p$i" + "_hw2', top: '90.0%', left: '65.0%', width: '12.0%', height: '2.5%', answer: 'answer7', placeholder: '...' }")
    }

    [void]$sb.AppendLine("        ]")
    [void]$sb.AppendLine("    },")
}

[void]$sb.AppendLine("};")

[System.IO.File]::WriteAllText("C:\Users\Mr Mahmoud Elziadi\Documents\GitHub\Englishtoon\js\p1_book_data.js", $sb.ToString(), [System.Text.Encoding]::UTF8)
